In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 230430

In [2]:
df_230430 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230430.csv')

/tmp/ipykernel_2193/883329192.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_230430 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230430.csv')

In [3]:
df_230430.head()

,event_datetime,session_id,device_id,event_key,description,location,devicemodel,language
0,2023-05-01 09:00:00,jgGFnoyc6GWuGIEgjp3nUoKRQbF3,cfc34eab-6930-488b-8109-70d37cec7dae,button,다음,signotherinputscreen,"iPhone10,4",ko-KR
1,2023-05-01 09:00:00,n3PI8GZnRFOKpJslIRgckMeRiln1,0dde2ecb-ff03-440f-98f3-94f20978b796,button,vote 선택,homevotesscreen,"iPhone14,4",ko-CA
2,2023-05-01 09:00:00,L31Dl8vRtdWPJ8XC0gGs1mPwzJH2,b50774ed-24ce-49e1-9383-945ff3aea9ff,button,친구선택,homeenquetescreen,SM-A125N,ko
3,2023-05-01 09:00:00,QjToElcYNkVxszJDHBhqtITlzDJ3,0999c6b6-c579-4c0f-916c-9a113010f84a,button,이름 셔플!,homeenquetescreen,SM-A305N,ko
4,2023-05-01 09:00:00,VRpXf303RGU730fIO4EjWstzAJi1,45985493-ed35-4cc5-935f-1bcf922e213c,button,앱바 뒤로가기,homefriendprofilescreen,"iPhone14,5",ko-KR

In [4]:
df_230430['event_key'].unique()

array(['button', '$session_end', '$session_start'], dtype=object)

# 230506

In [5]:
df_230506 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230506.csv')

In [6]:
df_230506.head()

,event_datetime,session_id,device_id,event_key,devicemodel,language
0,2023-05-07 09:00:00,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1,2023-05-07 09:00:00,CrFi87nvwiVvHExxP9uSfIHOmBy1,7770afa8-e228-4736-aa2a-658ebe2e3d25,$session_end,"iPhone12,8",ko-KR
2,2023-05-07 09:00:00,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
3,2023-05-07 09:00:00,4EFB4D45-0AAF-424A-8E4E-2F19249C8892,4efb4d45-0aaf-424a-8e4e-2f19249c8892,$session_start,"iPhone12,3",ko-KR
4,2023-05-07 09:00:00,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko

In [7]:
print('✅데이터 shape : ',df_230506.shape)
print('✅session_id nunique() : ',df_230506['session_id'].nunique())
print('✅device_id nunique() : ',df_230506['device_id'].nunique())

✅데이터 shape :  (7106588, 6)
✅session_id nunique() :  661365
✅device_id nunique() :  388976

In [8]:
display(df_230506[df_230506['session_id'] == 'OoWMTpTWpUa4m8I1RiKOk75Xnvs1'])

display(df_230506[df_230506['device_id'] == '498dbc0f-4537-41dc-93ec-f4406302a3b0'])

,event_datetime,session_id,device_id,event_key,devicemodel,language
0,2023-05-07 09:00:00,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
38282,2023-05-07 10:04:48,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
120412,2023-05-07 18:42:04,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
224724,2023-05-07 21:50:31,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
420093,2023-05-08 02:29:09,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
444537,2023-05-08 03:02:14,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
694491,2023-05-08 07:53:52,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
824490,2023-05-08 10:37:06,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
825153,2023-05-08 10:38:36,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1066749,2023-05-08 21:21:01,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1069397,2023-05-08 21:26:52,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1140339,2023-05-08 23:46:31,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1344476,2023-05-09 03:09:15,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1605249,2023-05-09 07:16:44,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1605500,2023-05-09 07:16:55,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
2467507,2023-05-10 05:06:51,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR

,event_datetime,session_id,device_id,event_key,devicemodel,language
0,2023-05-07 09:00:00,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
38282,2023-05-07 10:04:48,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
120412,2023-05-07 18:42:04,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
224724,2023-05-07 21:50:31,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
420093,2023-05-08 02:29:09,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
444537,2023-05-08 03:02:14,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
694491,2023-05-08 07:53:52,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
824490,2023-05-08 10:37:06,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
825153,2023-05-08 10:38:36,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1066749,2023-05-08 21:21:01,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1069397,2023-05-08 21:26:52,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1140339,2023-05-08 23:46:31,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1344476,2023-05-09 03:09:15,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
1605249,2023-05-09 07:16:44,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR
1605500,2023-05-09 07:16:55,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_end,"iPhone14,5",ko-KR
2467507,2023-05-10 05:06:51,OoWMTpTWpUa4m8I1RiKOk75Xnvs1,498dbc0f-4537-41dc-93ec-f4406302a3b0,$session_start,"iPhone14,5",ko-KR

In [9]:
display(df_230506[df_230506['session_id'] == 'JdxVFvtz6AcxxOZVvl6plHayjYJ3'])

display(df_230506[df_230506['device_id'] == '96348488-4d6a-49a8-8995-452718157fd7'])

,event_datetime,session_id,device_id,event_key,devicemodel,language
4,2023-05-07 09:00:00,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
1568671,2023-05-09 06:48:31,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
1613433,2023-05-09 07:22:42,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
2888897,2023-05-10 08:43:23,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
2939640,2023-05-10 09:19:12,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
3016544,2023-05-10 11:09:30,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko

,event_datetime,session_id,device_id,event_key,devicemodel,language
4,2023-05-07 09:00:00,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
1568671,2023-05-09 06:48:31,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
1612060,2023-05-09 07:21:57,96348488-4d6a-49a8-8995-452718157fd7,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
1613416,2023-05-09 07:22:41,96348488-4d6a-49a8-8995-452718157fd7,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
1613433,2023-05-09 07:22:42,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
2888897,2023-05-10 08:43:23,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
2939640,2023-05-10 09:19:12,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
2939641,2023-05-10 09:19:12,96348488-4d6a-49a8-8995-452718157fd7,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
3016358,2023-05-10 11:08:49,96348488-4d6a-49a8-8995-452718157fd7,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko
3016541,2023-05-10 11:09:29,96348488-4d6a-49a8-8995-452718157fd7,96348488-4d6a-49a8-8995-452718157fd7,$session_end,SM-A315N,ko
3016544,2023-05-10 11:09:30,JdxVFvtz6AcxxOZVvl6plHayjYJ3,96348488-4d6a-49a8-8995-452718157fd7,$session_start,SM-A315N,ko

In [10]:
display(df_230506[df_230506['session_id'] == 'W6frWgWJtbWTJwdm6eVWPGKwY2Y2	'])

display(df_230506[df_230506['device_id'] == '9fbdc45d-a74a-4d9f-9d40-0f400b72877e'])

Empty DataFrame
Columns: [event_datetime, session_id, device_id, event_key, devicemodel, language]
Index: []

,event_datetime,session_id,device_id,event_key,devicemodel,language
2,2023-05-07 09:00:00,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
151010,2023-05-07 19:49:48,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
152315,2023-05-07 19:52:11,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
191602,2023-05-07 20:59:57,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
255186,2023-05-07 22:34:07,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
303309,2023-05-07 23:43:17,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
461713,2023-05-08 03:25:02,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
505743,2023-05-08 04:22:22,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
731181,2023-05-08 08:31:30,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
833547,2023-05-08 11:01:04,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
866031,2023-05-08 15:51:41,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
926384,2023-05-08 17:14:39,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
927748,2023-05-08 17:15:34,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
1064652,2023-05-08 21:16:31,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
1319941,2023-05-09 02:45:37,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
1376955,2023-05-09 03:42:39,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
1500233,2023-05-09 05:46:01,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
1568496,2023-05-09 06:48:21,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
1859235,2023-05-09 16:27:35,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
1889169,2023-05-09 16:57:46,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
1890312,2023-05-09 16:58:50,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
1939937,2023-05-09 17:41:59,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
3123849,2023-05-10 16:56:28,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
3535588,2023-05-11 01:06:26,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
3545207,2023-05-11 01:12:49,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
3806141,2023-05-11 04:18:06,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
4313943,2023-05-11 09:45:14,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
4449283,2023-05-11 16:37:28,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
4458624,2023-05-11 16:43:47,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
4954602,2023-05-12 01:53:42,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
5433029,2023-05-12 07:09:54,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
5516825,2023-05-12 07:53:23,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
5561898,2023-05-12 08:16:52,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
5636644,2023-05-12 08:56:41,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
5725655,2023-05-12 10:09:29,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
5988211,2023-05-12 18:04:59,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
5989019,2023-05-12 18:06:08,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6010291,2023-05-12 18:42:46,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6010350,2023-05-12 18:42:52,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6113224,2023-05-12 21:18:55,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6114221,2023-05-12 21:20:22,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6431877,2023-05-13 02:03:31,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6708568,2023-05-13 04:59:30,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6762622,2023-05-13 05:32:45,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6762767,2023-05-13 05:32:51,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6819477,2023-05-13 06:07:48,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6821211,2023-05-13 06:08:52,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6886470,2023-05-13 06:49:05,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR
6889287,2023-05-13 06:50:47,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_end,"iPhone14,8",ko-KR
6988355,2023-05-13 07:44:36,W6frWgWJtbWTJwdm6eVWPGKwY2Y2,9fbdc45d-a74a-4d9f-9d40-0f400b72877e,$session_start,"iPhone14,8",ko-KR

In [11]:
df_230506['event_key'].unique()

array(['$session_end', '$session_start'], dtype=object)

# 230512

In [12]:
import pandas as pd

In [ ]:
df_230512 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230512_kst.csv')

In [65]:
df_230512_2 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230512.csv')

In [ ]:
df_230512_2 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230512.csv')

In [66]:
print('✅데이터 shape : ', df_230512_2.shape)
print('✅session_id nunique() : ',df_230512_2['session_id'].nunique())
print('✅device_id nunique() : ',df_230512_2['device_id'].nunique())

✅데이터 shape :  (12188804, 6)
✅session_id nunique() :  770980
✅device_id nunique() :  525224

In [51]:
print('✅데이터 shape : ',df_230512.shape)
print('✅session_id nunique() : ',df_230512['session_id'].nunique())
print('✅device_id nunique() : ',df_230512['device_id'].nunique())

✅데이터 shape :  (927087, 6)
✅session_id nunique() :  230249
✅device_id nunique() :  199349

In [ ]:
# 1. UTC 기준으로 파싱
df_230512_2['event_datetime'] = pd.to_datetime(df_230512_2['Asia/Seoul'], utc=True)

# 2. 한국시간(Asia/Seoul)으로 타임존 변환
df_230512_2['event_datetime'] = df_230512_2['event_datetime'].dt.tz_convert('Asia/Seoul')

In [52]:
df_230512.head()

,event_datetime,session_id,device_id,event_key,devicemodel,language
0,2023-05-13 09:00:00,6zkImM4PD0MHIbJ9zRVXs6vX6e62,cb7a48f6-6882-4223-98fd-4fe73cb3903b,$session_start,"iPhone14,4",ko-KR
1,2023-05-13 09:00:00,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_end,"iPhone12,8",ko-KR
2,2023-05-13 09:00:00,RyWeiMNMACUhbawb63ITBMX1c1U2,75f9bcd9-78c8-4dd6-a91e-0faf85a10526,$session_end,"iPhone15,2",ko-KR
3,2023-05-13 09:00:00,3OaNLuqTVDTkMEc8IsZNBxF9hsH2,380ebcac-4f9d-4004-968d-cf6372908adc,$session_start,"iPhone12,1",en-KR
4,2023-05-13 09:00:00,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR

In [53]:
display(df_230512[df_230512['session_id'] == 'Sq5vui6fg2Nhz2EHeC8e4PWyxo13'])

display(df_230512[df_230512['device_id'] == 'b2512274-1161-4fd2-a4e8-b40f1ecc0372'])

,event_datetime,session_id,device_id,event_key,devicemodel,language
1,2023-05-13 09:00:00,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_end,"iPhone12,8",ko-KR
86318,2023-05-13 10:05:39,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_start,"iPhone12,8",ko-KR
184389,2023-05-13 16:56:05,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_end,"iPhone12,8",ko-KR
818779,2023-05-14 00:22:50,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_start,"iPhone12,8",ko-KR

,event_datetime,session_id,device_id,event_key,devicemodel,language
1,2023-05-13 09:00:00,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_end,"iPhone12,8",ko-KR
86318,2023-05-13 10:05:39,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_start,"iPhone12,8",ko-KR
184389,2023-05-13 16:56:05,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_end,"iPhone12,8",ko-KR
818779,2023-05-14 00:22:50,Sq5vui6fg2Nhz2EHeC8e4PWyxo13,b2512274-1161-4fd2-a4e8-b40f1ecc0372,$session_start,"iPhone12,8",ko-KR

In [17]:
display(df_230512[df_230512['session_id'] == 'rWBKAsEaG3cpHuAPRyohFr3k6PB2'])

display(df_230512[df_230512['device_id'] == '290b1a00-659d-4d24-a26d-5524d7ac44ce'])

,Asia/Seoul,session_id,device_id,event_key,devicemodel,language
4,2023-05-13T00:00:00.070Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
74824,2023-05-13T00:54:20.935Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
270022,2023-05-13T09:38:52.223Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
388662,2023-05-13T11:08:00.810Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
597497,2023-05-13T13:11:00.104Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
...,...,...,...,...,...,...
8944961,2023-05-17T14:46:38.239Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
9043851,2023-05-17T15:41:29.294Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
9181651,2023-05-17T16:41:31.148Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
9864406,2023-05-17T21:31:03.718Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
9865562,2023-05-17T21:31:30.443Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR

,Asia/Seoul,session_id,device_id,event_key,devicemodel,language
4,2023-05-13T00:00:00.070Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
74824,2023-05-13T00:54:20.935Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
270022,2023-05-13T09:38:52.223Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
388662,2023-05-13T11:08:00.810Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
597497,2023-05-13T13:11:00.104Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
...,...,...,...,...,...,...
8944961,2023-05-17T14:46:38.239Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
9043851,2023-05-17T15:41:29.294Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
9181651,2023-05-17T16:41:31.148Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR
9864406,2023-05-17T21:31:03.718Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_start,"iPhone14,3",ko-KR
9865562,2023-05-17T21:31:30.443Z,rWBKAsEaG3cpHuAPRyohFr3k6PB2,290b1a00-659d-4d24-a26d-5524d7ac44ce,$session_end,"iPhone14,3",ko-KR

In [18]:
df_230512['event_key'].unique()

array(['$session_start', '$session_end'], dtype=object)

# 230518

In [19]:
df_230518 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230518.csv')

In [20]:
print('✅데이터 shape : ',df_230518.shape)
print('✅session_id nunique() : ',df_230518['session_id'].nunique())
print('✅device_id nunique() : ',df_230518['device_id'].nunique())

✅데이터 shape :  (8224556, 6)
✅session_id nunique() :  693069
✅device_id nunique() :  534907

In [21]:
df_230512['event_key'].unique()

array(['$session_start', '$session_end'], dtype=object)

# 230524

In [35]:
df_230524 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230524.csv')

In [37]:
df_230524['event_key'].unique()

array(['$session_start'], dtype=object)

# 230530

In [24]:
df_230530 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230530.csv')

In [25]:
df_230512['event_key'].unique()

array(['$session_start', '$session_end'], dtype=object)

# 230605

In [26]:
df_230605 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230605.csv')

# 230611

In [44]:
df_230611 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230611.csv')

# 230617

In [28]:
df_230617 = pd.read_csv('/home/leesh/codeit_project/codeit-project-docker/notebooks/data/df_230617.csv')

# EVENT_KEY

In [54]:
print('✅230430 :',df_230430['event_key'].unique())
print('✅230506 :',df_230506['event_key'].unique())
print('✅230512 :',df_230512['event_key'].unique())
print('✅230518 :',df_230518['event_key'].unique())
print('✅230524 :',df_230524['event_key'].unique())
print('✅230530 :',df_230530['event_key'].unique())
print('✅230605 :',df_230605['event_key'].unique())
print('✅230611 :',df_230611['event_key'].unique())

✅230430 : ['button' '$session_end' '$session_start']
✅230506 : ['$session_end' '$session_start']
✅230512 : ['$session_start' '$session_end' nan]
✅230518 : ['$session_start' '$session_end']
✅230524 : ['$session_start']
✅230530 : ['$session_start']
✅230605 : ['$session_start']
✅230611 : ['$session_start']

# event_datetime

In [60]:
print('✅230430 :',df_230430['event_datetime'].min(),df_230430['event_datetime'].max())
print('✅230506 :',df_230506['event_datetime'].min(),df_230506['event_datetime'].max())
print('✅230512 :',df_230524['event_datetime'].min(),df_230512['event_datetime'].max())
print('✅230518 :',df_230518['event_datetime'].min(),df_230518['event_datetime'].max())
print('✅230524 :',df_230524['event_datetime'].min(),df_230524['event_datetime'].max())
print('✅230530 :',df_230530['event_datetime'].min(),df_230530['event_datetime'].max())
print('✅230605 :',df_230605['event_datetime'].min(),df_230605['event_datetime'].max())
print('✅230611 :',df_230611['event_datetime'].min(),df_230611['event_datetime'].max())

✅230430 : 2023-05-01 09:00:00 2023-05-07 08:59:59
✅230506 : 2023-05-07 09:00:00 2023-05-13 08:59:59
✅230512 : 2023-05-25 09:00:00 2023-05-14 01:27:40
✅230518 : 2023-05-19 09:00:00 2023-05-25 08:59:59
✅230524 : 2023-05-25 09:00:00 2023-05-31 08:56:42
✅230530 : 2023-05-31 09:01:06 2023-06-06 08:55:03
✅230605 : 2023-06-06 09:01:35 2023-06-12 08:45:59
✅230611 : 2023-06-12 09:00:33 2023-06-18 08:26:07

In [61]:
display(df_230430.head())
display(df_230430.info())

df_230430['event_datetime'] = pd.to_datetime(df_230430['event_datetime'])
df_230506['event_datetime'] = pd.to_datetime(df_230506['event_datetime'])
df_230512['event_datetime'] = pd.to_datetime(df_230512['event_datetime'])
df_230518['event_datetime'] = pd.to_datetime(df_230518['event_datetime'])
df_230524['event_datetime'] = pd.to_datetime(df_230524['event_datetime'])
df_230530['event_datetime'] = pd.to_datetime(df_230530['event_datetime'])
df_230605['event_datetime'] = pd.to_datetime(df_230605['event_datetime'])
df_230611['event_datetime'] = pd.to_datetime(df_230611['event_datetime'])
df_230617['event_datetime'] = pd.to_datetime(df_230617['event_datetime'])

,event_datetime,session_id,device_id,event_key,description,location,devicemodel,language,date,time
0,2023-05-01 09:00:00,jgGFnoyc6GWuGIEgjp3nUoKRQbF3,cfc34eab-6930-488b-8109-70d37cec7dae,button,다음,signotherinputscreen,"iPhone10,4",ko-KR,2023-05-01,09:00:00
1,2023-05-01 09:00:00,n3PI8GZnRFOKpJslIRgckMeRiln1,0dde2ecb-ff03-440f-98f3-94f20978b796,button,vote 선택,homevotesscreen,"iPhone14,4",ko-CA,2023-05-01,09:00:00
2,2023-05-01 09:00:00,L31Dl8vRtdWPJ8XC0gGs1mPwzJH2,b50774ed-24ce-49e1-9383-945ff3aea9ff,button,친구선택,homeenquetescreen,SM-A125N,ko,2023-05-01,09:00:00
3,2023-05-01 09:00:00,QjToElcYNkVxszJDHBhqtITlzDJ3,0999c6b6-c579-4c0f-916c-9a113010f84a,button,이름 셔플!,homeenquetescreen,SM-A305N,ko,2023-05-01,09:00:00
4,2023-05-01 09:00:00,VRpXf303RGU730fIO4EjWstzAJi1,45985493-ed35-4cc5-935f-1bcf922e213c,button,앱바 뒤로가기,homefriendprofilescreen,"iPhone14,5",ko-KR,2023-05-01,09:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8588422 entries, 0 to 8588421
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   event_datetime  datetime64[ns]
 1   session_id      object
 2   device_id       object
 3   event_key       object
 4   description     object
 5   location        object
 6   devicemodel     object
 7   language        object
 8   date            object
 9   time            object
dtypes: datetime64[ns](1), object(9)
memory usage: 655.2+ MB

None

In [62]:
df_230430['date'] = df_230430['event_datetime'].dt.date
df_230506['date'] = df_230506['event_datetime'].dt.date
df_230512['date'] = df_230512['event_datetime'].dt.date
df_230518['date'] = df_230518['event_datetime'].dt.date
df_230524['date'] = df_230524['event_datetime'].dt.date
df_230530['date'] = df_230530['event_datetime'].dt.date
df_230605['date'] = df_230605['event_datetime'].dt.date
df_230611['date'] = df_230611['event_datetime'].dt.date
df_230617['date'] = df_230617['event_datetime'].dt.date


df_230430['time'] = df_230430['event_datetime'].dt.time
df_230506['time'] = df_230506['event_datetime'].dt.time
df_230512['time'] = df_230512['event_datetime'].dt.time
df_230518['time'] = df_230518['event_datetime'].dt.time
df_230524['time'] = df_230524['event_datetime'].dt.time
df_230530['time'] = df_230530['event_datetime'].dt.time
df_230605['time'] = df_230605['event_datetime'].dt.time
df_230611['time'] = df_230611['event_datetime'].dt.time
df_230617['time'] = df_230617['event_datetime'].dt.time

In [63]:
date_list = [df_230430, df_230506, df_230512, df_230518, df_230524, df_230530, df_230605, df_230611, df_230617]
date_names = ['230430', '230506', '230512' ,'230518', '230524', '230530', '230605', '230611', '230617']

for name, data in zip(date_names, date_list):
    print(f"📅 날짜: {name}")
    print(data['date'].unique(), "\n")

📅 날짜: 230430
[datetime.date(2023, 5, 1) datetime.date(2023, 5, 2)
 datetime.date(2023, 5, 3) datetime.date(2023, 5, 4)
 datetime.date(2023, 5, 5) datetime.date(2023, 5, 6)
 datetime.date(2023, 5, 7)]

📅 날짜: 230506
[datetime.date(2023, 5, 7) datetime.date(2023, 5, 8)
 datetime.date(2023, 5, 9) datetime.date(2023, 5, 10)
 datetime.date(2023, 5, 11) datetime.date(2023, 5, 12)
 datetime.date(2023, 5, 13)]

📅 날짜: 230512
[datetime.date(2023, 5, 13) datetime.date(2023, 5, 14)]

📅 날짜: 230518
[datetime.date(2023, 5, 19) datetime.date(2023, 5, 20)
 datetime.date(2023, 5, 21) datetime.date(2023, 5, 22)
 datetime.date(2023, 5, 23) datetime.date(2023, 5, 24)
 datetime.date(2023, 5, 25)]

📅 날짜: 230524
[datetime.date(2023, 5, 25) datetime.date(2023, 5, 26)
 datetime.date(2023, 5, 27) datetime.date(2023, 5, 28)
 datetime.date(2023, 5, 29) datetime.date(2023, 5, 30)
 datetime.date(2023, 5, 31)]

📅 날짜: 230530
[datetime.date(2023, 5, 31) datetime.date(2023, 6, 1)
 datetime.date(2023, 6, 2) datetime.date(2023, 6, 3)
 datetime.date(2023, 6, 4) datetime.date(2023, 6, 5)
 datetime.date(2023, 6, 6)]

📅 날짜: 230605
[datetime.date(2023, 6, 6) datetime.date(2023, 6, 7)
 datetime.date(2023, 6, 8) datetime.date(2023, 6, 9)
 datetime.date(2023, 6, 10) datetime.date(2023, 6, 11)
 datetime.date(2023, 6, 12)]

📅 날짜: 230611
[datetime.date(2023, 6, 12) datetime.date(2023, 6, 13)
 datetime.date(2023, 6, 14) datetime.date(2023, 6, 15)
 datetime.date(2023, 6, 16) datetime.date(2023, 6, 17)
 datetime.date(2023, 6, 18)]

📅 날짜: 230617
[datetime.date(2023, 6, 18) datetime.date(2023, 6, 19)
 datetime.date(2023, 6, 20) datetime.date(2023, 6, 21)
 datetime.date(2023, 6, 22) datetime.date(2023, 6, 23)
 datetime.date(2023, 6, 24)]

In [64]:
df_230611.head()

,event_datetime,device_id,event_key,devicemodel,language,date,time
0,2023-06-12 09:00:33,8A5F41F9-D126-453C-8EA8-E0C2484584E3,$session_start,"iPhone13,1",ko-KR,2023-06-12,09:00:33
1,2023-06-12 09:10:18,A81A2A45-6260-41C6-B81B-071F006D60BD,$session_start,"iPhone14,2",ko-KR,2023-06-12,09:10:18
2,2023-06-12 09:17:21,CD41A81E-8D5C-4E7A-8289-587AD8C306F5,$session_start,"iPhone13,1",ko-KR,2023-06-12,09:17:21
3,2023-06-12 09:21:00,5A92997F-362C-400B-8613-893A2FD6197F,$session_start,"iPhone13,2",ko-KR,2023-06-12,09:21:00
4,2023-06-12 09:22:44,7FB46B64-B405-49C4-9378-8FABA73D4038,$session_start,"iPad13,16",ko-KR,2023-06-12,09:22:44