# DA05 고급프로젝트 1팀 김연우

# 파일 불러오기

### votes 파일

In [ ]:
import pandas as pd

# 파일 경로 지정 (votes)
path_timelinereport = "gs://codeit-project/votes/accounts_timelinereport.parquet"
path_friendrequest = "gs://codeit-project/votes/accounts_friendrequest.parquet"
path_attendance    = "gs://codeit-project/votes/accounts_attendance.parquet"
path_blockrecord    = "gs://codeit-project/votes/accounts_blockrecord.parquet"        
path_failpaymenthistory = "gs://codeit-project/votes/accounts_failpaymenthistory.parquet"
path_group = "gs://codeit-project/votes/accounts_group.parquet"
path_nearbyschool = "gs://codeit-project/votes/accounts_nearbyschool.parquet"
path_paymenthistory = "gs://codeit-project/votes/accounts_paymenthistory.parquet"
path_pointhistory = "gs://codeit-project/votes/accounts_pointhistory.parquet"
path_school = "gs://codeit-project/votes/accounts_school.parquet"
path_user = "gs://codeit-project/votes/accounts_user.parquet"
path_user_contacts = "gs://codeit-project/votes/accounts_user_contacts.parquet"
path_userquestionrecord = "gs://codeit-project/votes/accounts_userquestionrecord.parquet"
path_userwithdraw  = "gs://codeit-project/votes/accounts_userwithdraw.parquet"
path_receipts = "gs://codeit-project/votes/event_receipts.parquet"
path_event = "gs://codeit-project/votes/events.parquet"
path_question = "gs://codeit-project/votes/polls_question.parquet"
path_questionpiece  = "gs://codeit-project/votes/polls_questionpiece.parquet"
path_questionreport = "gs://codeit-project/votes/polls_questionreport.parquet"
path_questionset = "gs://codeit-project/votes/polls_questionset.parquet"
path_usercandidate = "gs://codeit-project/votes/polls_usercandidate.parquet"

# 파일 불러오기 (votes)
timelinereport = pd.read_parquet(path_timelinereport, storage_options={"token": None})
friendrequest = pd.read_parquet(path_friendrequest, storage_options={"token": None})
attendance = pd.read_parquet(path_attendance, storage_options={"token": None})
blockrecord = pd.read_parquet(path_blockrecord, storage_options={"token": None})
failpaymenthistory = pd.read_parquet(path_failpaymenthistory, storage_options={"token": None})
group = pd.read_parquet(path_group, storage_options={"token": None})
nearbyschool = pd.read_parquet(path_nearbyschool, storage_options={"token": None})
paymenthistory = pd.read_parquet(path_paymenthistory, storage_options={"token": None})
pointhistory = pd.read_parquet(path_pointhistory, storage_options={"token": None})
school = pd.read_parquet(path_school, storage_options={"token": None})
user = pd.read_parquet(path_user, storage_options={"token": None})
user_contacts = pd.read_parquet(path_user_contacts, storage_options={"token": None})
userquestionrecord = pd.read_parquet(path_userquestionrecord, storage_options={"token": None})
userwithdraw = pd.read_parquet(path_userwithdraw, storage_options={"token": None})
receipts = pd.read_parquet(path_receipts, storage_options={"token": None})
event = pd.read_parquet(path_event, storage_options={"token": None})
question = pd.read_parquet(path_question, storage_options={"token": None})
questionpiece = pd.read_parquet(path_questionpiece, storage_options={"token": None})
questionreport = pd.read_parquet(path_questionreport, storage_options={"token": None})
questionset = pd.read_parquet(path_questionset, storage_options={"token": None})
usercandidate = pd.read_parquet(path_usercandidate, storage_options={"token": None})

### hackle 파일

In [1]:
import pandas as pd

# 파일 경로 지정 (hackle)

path_device_properties = "gs://codeit-project/hackle/device_properties.parquet"
path_hackle_events  = "gs://codeit-project/hackle/hackle_events.parquet"    
path_hackle_properties = "gs://codeit-project/hackle/hackle_properties.parquet"
path_user_properties = "gs://codeit-project/hackle/user_properties.parquet"

# 파일 불러오기 (hackle)
device_properties = pd.read_parquet(path_device_properties, storage_options={"token": None})
hackle_events = pd.read_parquet(path_hackle_events, storage_options={"token": None})
hackle_properties = pd.read_parquet(path_hackle_properties, storage_options={"token": None})
user_properties = pd.read_parquet(path_user_properties, storage_options={"token": None})

### votes 파일 테이블 설명

| 번호 | 테이블 명 | 설명
|---|------------------|------------|
|1	|attendance	|출석 테이블|
|2	|blockrecord	|차단 기록 테이블	|
|3	|failpaymenthistory	|상품 구매 실패 기록 테이블	|
|4	|friendrequest	|친구 요청 테이블	|
|5	|group	|학급 테이블	|
|6	|nearbyschool	|가까운 학교를 기록해두기 위한 관계형 테이블|	
|7	|paymenthistory	|구매 기록 테이블	|
|8	|user_contacts	|유저 컨택 테이블	|
|9	|pointhistory	|포인트 기록 테이블	|
|10	|school	|학교 테이블	|
|11	|timelinereport	|유저 신고기록 테이블|	
|12	|user	|유저 테이블|	
|13	|userquestionrecord	|투표 기록 테이블	|
|14	|userwithdraw	|포인트 이벤트 참여 테이블|	
|15	|event_receipts		||
|16	|events	|포인트 이벤트 테이블|	
|17	|question	|질문 내용 테이블|	
|18	|questionpiece	|질문에 대한 신고 기록 테이블	한 질문 세트는 10개의 질문으로 구성됩니다.|
|19	|questionreport	|	|
|20	|questionset	|질문 세트 데이블 	유저가 질문 한 세트에 대한 답변을 끝낼때 생성되는 데이터입니다.|
|21	|usercandidate	|질문에 등장하는 유저들 테이블	한 질문마다 최대 8명이 등장합니다.|

### 1. hackle테이블 명세

| 컬럼명         | 컬럼 설명     | 비고 |
|----------------|---------------|------|
| session_id     | 세션 식별자   |      |
| user_id        | 사용자 ID     |      |
| language       | 사용 언어     |      |
| osname         | 운영 체제 이름 |      |
| osversion      | 운영 체제 버전 |      |
| versionname    | 앱 버전 이름  |      |
| device_id      | 장치 ID       |      |

| 컬럼명         | 컬럼 설명   | 비고 |
|----------------|-------------|------|
| device_id      | 장치 ID     |      |
| device_model   | 장치 모델명 |      |
| device_vendor  | 장치 제조사 |      |

| 컬럼명         | 컬럼 설명             | 비고 |
|----------------|------------------------|------|
| event_id       | 고유 이벤트 ID         |      |
| event_datetime | 이벤트 발생 시간       |      |
| event_key      | 이벤트 키              |      |
| session_id     | 세션 ID                |      |
| item_name      | 이벤트 관련 아이템 이름 |     |
| page_name      | 이벤트 발생 페이지 이름 |     |
| friend_count   | 친구 수                |      |
| votes_count    | 받은 투표 수           |      |
| heart_balance  | 잔여 하트              |      |
| question_id    | 고유 질문 ID           |      |
| 컬럼명   | 컬럼 설명     | 비고 |
|----------|---------------|------|
| class    | 사용자 반     |      |
| gender   | 사용자 성별   |      |
| grade    | 사용자 학년   |      |
| school_id| 사용자 학교 ID |     |

### hackle 이벤트 목록

| 번호 | 이벤트명                         | 이벤트 설명                                           | 비고       |
|------|----------------------------------|--------------------------------------------------------|------------|
| 1    | $session_start                   | 세션 시작                                              |            |
| 2    | $session_end                     | 세션 종료                                              |            |
| 3    | button                           | -                                                      | 전처리 대상 |
| 4    | click_appbar_alarm_center        | 상단 appbar에서 알림 모양 클릭                         |            |
| 5    | click_appbar_chat_rooms          | 상단 appbar에서 메시지 모양 클릭                       |            |
| 6    | click_appbar_friend_plus         | 상단 appbar에서 친구 모양 클릭                         |            |
| 7    | click_appbar_setting             | -                                                      | 전처리 대상 |
| 8    | click_attendance                 | 출석체크 클릭                                          |            |
| 9    | click_autoadd_contact            | 친구 추천 탭 위의 연락처 자동 친구 추가하기 버튼 클릭 |            |
| 10   | click_bottom_navigation_lab      | 하단 네비게이션에서 lab 클릭                           |            |
| 11   | click_bottom_navigation_profile  | 하단 네비게이션에서 프로필 클릭                        |            |
| 12   | click_bottom_navigation_questions| 하단 네비게이션에서 질문 클릭                          |            |
| 13   | click_bottom_navigation_timeline | 하단 네비게이션에서 타임라인 클릭                      |            |
| 14   | click_community_chat             | 채팅 클릭                                              |            |
| 15   | click_copy_profile_link_ask      | ask에서 내 프로필 링크 복사하기 클릭                   |            |
| 16   | click_copy_profile_link_profile  | 본인 프로필 링크 복사하기 클릭                         |            |
| 17   | click_friend_invite              | 질문 대기상태에서 친구 초대하고 바로 받기 클릭        |            |
| 18   | click_invite_friend              | ask에서 친구 초대하기 클릭                             |            |
| 19   | click_notice                     | 알림 센터 클릭                                         |            |
| 20   | click_notice_detail              | 알림 센터 디테일에서 특정 알림을 클릭                 |            |
| 21   | click_profile_ask                | 친구 프로필에서 ‘친구에게 글을 남길까?’ 클릭           |            |
| 22   | click_purchase                   | 구매할 하트 상품 클릭                                  |            |
| 23   | click_question_ask               | 홈화면에서 ask 클릭                                    |            |
| 24   | click_question_open              | 받은 질문을 열 때                                      |            |
| 25   | click_question_share             | 받은 질문을 공유할 때                                  |            |
| 26   | click_question_start             | 홈화면에서 질문 start 클릭                             |            |
| 27   | click_random_ask_normal          | 기존 타임라인에서 일반적인 ask 클릭                   |            |
| 28   | click_random_ask_other           | 기존 타임라인에서 다른 친구에게 글 남기기 클릭        |            |
| 29   | click_random_ask_shuffle         | 기존 타임라인에서 ask 랜덤 셔플 클릭                  |            |
| 30   | click_timeline_chat_start        | 기존 타임라인에서 채팅 클릭                           |            |
| 31   | complete_purchase                | 하트 구입 완료                                         |            |
| 32   | complete_question                | 질문 완료                                              |            |
| 33   | complete_signup                  | 회원가입 완료                                          |            |
| 34   | launch_app                       | 앱 실행                                                |            |
| 35   | skip_question                    | 질문 스킵                                              |            |
| 36   | view_friendplus_tap              | 친구 추천 화면 진입                                    |            |
| 37   | view_home_tap                    | 홈 진입                                                |            |
| 38   | view_lab_tap                     | 실험실 탭에 진입                                       |            |
| 39   | view_login                       | 로그인 페이지 진입                                     |            |
| 40   | view_profile_tap                 | 프로필 화면 진입                                       |            |
| 41   | view_questions_tap               | 질문 화면 진입                                         |            |
| 42   | view_shop                        | 하트 충전소 진입                                       |            |
| 43   | view_signup                      | 회원가입 페이지 진입                                   |            |
| 44   | view_timeline_tap                | 타임라인 화면 진입                                     |            |

# 데이터 EDA

In [5]:
timelinereport

,id,reason,created_at,reported_user_id,user_id,user_question_record_id
0,28,타인을 사칭함,2023-05-06 04:44:57,874587,885082,3920588
1,37,친구를 비하하거나 조롱하는 어투,2023-05-06 05:41:19,881048,881298,4018679
2,46,친구를 비하하거나 조롱하는 어투,2023-05-06 06:26:59,887882,881945,4120914
3,64,허위 사실 언급,2023-05-06 07:07:46,888610,893684,4143049
4,65,허위 사실 언급,2023-05-06 07:07:52,888610,893684,4143049
...,...,...,...,...,...,...
203,21857,선정적이거나 폭력적인 내용,2023-05-29 15:42:50,1479859,1402487,131364422
204,22634,허위 사실 언급,2023-05-31 10:33:00,1551005,1161757,135982670
205,22635,허위 사실 언급,2023-05-31 10:33:06,1551005,1161757,134909577
206,23022,선정적이거나 폭력적인 내용,2023-06-01 16:02:33,1479859,1498172,139837310
207,23108,친구를 비하하거나 조롱하는 어투,2023-06-02 08:30:06,1562736,1548002,140765885

In [8]:
friendrequest

,id,status,created_at,updated_at,receive_user_id,send_user_id
0,7,P,2023-04-17 18:29:11,2023-04-17 18:29:11,831962,837521
1,10,A,2023-04-17 18:29:11,2023-04-22 06:02:53,832151,837521
2,11,A,2023-04-17 18:29:11,2023-04-18 19:28:41,832340,837521
3,13,A,2023-04-17 18:29:11,2023-04-19 11:05:04,833041,837521
4,20,P,2023-04-17 18:29:11,2023-04-17 18:29:11,834415,837521
...,...,...,...,...,...,...
17147170,19692975,P,2024-05-09 07:24:50,2024-05-09 07:24:50,1583730,1583731
17147171,19692976,A,2024-05-09 07:31:41,2024-05-09 07:33:06,1583731,1583673
17147172,19692977,P,2024-05-09 08:20:44,2024-05-09 08:20:44,1299129,1575671
17147173,19692978,R,2024-05-09 09:19:40,2024-05-09 09:19:43,1304403,1392729
17147174,19692979,P,2024-05-09 09:21:47,2024-05-09 09:21:47,1304403,1392729