In [2]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from datetime import timedelta
import matplotlib.font_manager as fm
import matplotlib as mpl
import ast
import json
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

from collections import Counter
from kiwipiepy import Kiwi

In [3]:
def read_parquet_from_gcs(file_names, gcs_prefix, key_path):
    dfs = {}
    for name in file_names:
        path = f"{gcs_prefix}/{name}.parquet"
        dfs[name] = pd.read_parquet(path, storage_options={"token": key_path})
    return dfs


file_list = [
    "accounts_attendance",
    "accounts_blockrecord",
    "accounts_failpaymenthistory",
    "accounts_friendrequest",
    "accounts_group",
    "accounts_nearbyschool",
    "accounts_paymenthistory",
    "accounts_user_contacts",
    "accounts_pointhistory",
    "accounts_school",
    "accounts_timelinereport",
    "accounts_user",
    "accounts_userquestionrecord",
    "accounts_userwithdraw",
    "event_receipts",
    "events",
    "polls_question",
    "polls_questionpiece",
    "polls_questionreport",
    "polls_questionset",
    "polls_usercandidate"
]

gcs_prefix = "gs://codeit-project/votes"
key_path = "./config/key.json"

dfs = read_parquet_from_gcs(file_list, gcs_prefix, key_path)

# 출석 테이블
accounts_attendance = dfs["accounts_attendance"]

# 차단 기록 테이블
accounts_blockrecord = dfs["accounts_blockrecord"]

# 상품 구매 실패 기록 테이블
accounts_failpaymenthistory = dfs["accounts_failpaymenthistory"]

# 친구 요청 테이블
accounts_friendrequest = dfs["accounts_friendrequest"]

# 그룹 테이블
accounts_group = dfs["accounts_group"]

# 근처 학교 테이블
accounts_nearbyschool = dfs["accounts_nearbyschool"]

# 결제 기록 테이블
accounts_paymenthistory = dfs["accounts_paymenthistory"]

# 사용자 연락처 테이블
accounts_user_contacts = dfs["accounts_user_contacts"]

# 포인트 내역 테이블
accounts_pointhistory = dfs["accounts_pointhistory"]

# 학교 정보 테이블
accounts_school = dfs["accounts_school"]

# 타임라인 신고 기록 테이블
accounts_timelinereport = dfs["accounts_timelinereport"]

# 사용자 기본 정보 테이블
accounts_user = dfs["accounts_user"]

# 사용자 질문 응답 기록 테이블
accounts_userquestionrecord = dfs["accounts_userquestionrecord"]

# 회원 탈퇴 기록 테이블
accounts_userwithdraw = dfs["accounts_userwithdraw"]

# 이벤트 영수증 테이블
event_receipts = dfs["event_receipts"]

# 이벤트 테이블
events = dfs["events"]

# 질문 테이블
polls_question = dfs["polls_question"]

# 질문 조각 테이블
polls_questionpiece = dfs["polls_questionpiece"]

# 질문 신고 테이블
polls_questionreport = dfs["polls_questionreport"]

# 질문 세트 테이블
polls_questionset = dfs["polls_questionset"]

# 사용자 후보 응답 테이블
polls_usercandidate = dfs["polls_usercandidate"]

In [4]:
accounts_attendance.head()

   id                               attendance_date_list  user_id
0   1  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1446852
1   2  ["2023-05-27", "2023-05-29", "2023-05-30", "20...  1359398
2   3  ["2023-05-27", "2023-05-29", "2023-05-30", "20...  1501542
3   4  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1507767
4   5  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1287453

In [5]:
accounts_failpaymenthistory.head()

   id   productId phone_type          created_at  user_id
0   6   heart.200          A 2023-05-14 05:49:22  1055891
1   7   heart.777          A 2023-05-14 08:17:21  1152151
2   8   heart.777          A 2023-05-14 10:11:46   986200
3   9  heart.1000          A 2023-05-14 11:53:09  1028261
4  10   heart.777          A 2023-05-14 12:30:47  1235730

In [6]:
accounts_failpaymenthistory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          163 non-null    int64
 1   productId   56 non-null     object
 2   phone_type  163 non-null    object
 3   created_at  163 non-null    datetime64[ns]
 4   user_id     163 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 6.5+ KB

In [7]:
accounts_failpaymenthistory.isna().sum()

id              0
productId     107
phone_type      0
created_at      0
user_id         0
dtype: int64

In [8]:
accounts_friendrequest.head()

   id status          created_at          updated_at  receive_user_id  send_user_id
0   7      P 2023-04-17 18:29:11 2023-04-17 18:29:11           831962        837521
1  10      A 2023-04-17 18:29:11 2023-04-22 06:02:53           832151        837521
2  11      A 2023-04-17 18:29:11 2023-04-18 19:28:41           832340        837521
3  13      A 2023-04-17 18:29:11 2023-04-19 11:05:04           833041        837521
4  20      P 2023-04-17 18:29:11 2023-04-17 18:29:11           834415        837521

In [9]:
# 중복행 탐색
accounts_friendrequest.duplicated().sum()

np.int64(0)

In [10]:
accounts_group[accounts_group['school_id'] == 4383].sort_values(by  = 'grade', ascending = True)

          id  grade  class_num  school_id
40592  40614      1          2       4383
54375  54400      1          3       4383
58686  58711      1          4       4383
70593  70619      1          5       4383
70614  70640      1          6       4383
76437  76464      1          4       4383
71595  71621      2          5       4383
68448  68474      2          1       4383
75729  75756      2          3       4383
75559  75586      2          4       4383
75940  75967      2          2       4383
75187  75214      2          6       4383
76118  76145      2         20       4383
75733  75760      3          5       4383
75570  75597      3          3       4383
73264  73290      3          4       4383
75824  75851      3          2       4383
75735  75762      3          1       4383
79779  79806      3          1       4383

In [11]:
accounts_user.head()

       id  is_superuser  is_staff gender  point                                     friend_id_list  is_push_on                 created_at block_user_id_list hide_user_id_list ban_status  report_count  alarm_count  pending_chat  pending_votes  group_id
0  831956             1         1   None    600  [1292473, 913158, 1488461, 1064695, 1043565, 1...           0 2023-03-29 03:44:14.047130                 []                []          N             0            0             0              0       NaN
1  831962             0         0      F   2248  [833025, 832642, 982531, 879496, 838541, 83752...           1 2023-03-29 05:18:56.162368                 []                []          N           253        40878          5499            110      12.0
2  832151             0         0      M   1519  [838785, 982531, 882567, 879496, 838541, 83649...           0 2023-03-29 12:56:34.989468                 []                []          N             0           37             0             47       1.0
3  832340             0         0      F     57  [841345, 982531, 838785, 963714, 882567, 83252...           1 2023-03-29 12:56:35.020790                 []                []          N             0           19             0             21       1.0
4  832520             0         0      M   1039  [874050, 849763, 874212, 844297, 838541, 84004...           0 2023-03-29 12:56:35.049311                 []                []          N             0           29             0             15      12.0

In [12]:
accounts_userquestionrecord.head()

       id status          created_at  chosen_user_id  question_id  user_id  question_piece_id  has_read answer_status   answer_updated_at  report_count  opened_times
0  771777      C 2023-04-28 12:27:49          849469          252   849436             998458         0             N 2023-04-28 12:27:49             0             0
1  771800      C 2023-04-28 12:28:02          849446          244   849436             998459         0             N 2023-04-28 12:28:02             0             0
2  771812      C 2023-04-28 12:28:09          849454          183   849436             998460         1             N 2023-04-28 12:28:09             0             0
3  771828      C 2023-04-28 12:28:16          847375          101   849436             998461         0             N 2023-04-28 12:28:16             0             0
4  771851      C 2023-04-28 12:28:26          849477          209   849436             998462         1             N 2023-04-28 12:28:26             0             0

In [13]:
accounts_userquestionrecord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1217558 entries, 0 to 1217557
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1217558 non-null  int64
 1   status             1217558 non-null  object
 2   created_at         1217558 non-null  datetime64[ns]
 3   chosen_user_id     1217558 non-null  int64
 4   question_id        1217558 non-null  int64
 5   user_id            1217558 non-null  int64
 6   question_piece_id  1217558 non-null  int64
 7   has_read           1217558 non-null  int64
 8   answer_status      1217558 non-null  object
 9   answer_updated_at  1217558 non-null  datetime64[ns]
 10  report_count       1217558 non-null  int64
 11  opened_times       1217558 non-null  int64
dtypes: datetime64[ns](2), int64(8), object(2)
memory usage: 111.5+ MB

In [14]:
accounts_userquestionrecord[accounts_userquestionrecord['user_id'] == 849436]

                id status          created_at  chosen_user_id  question_id  user_id  question_piece_id  has_read answer_status   answer_updated_at  report_count  opened_times
0           771777      C 2023-04-28 12:27:49          849469          252   849436             998458         0             N 2023-04-28 12:27:49             0             0
1           771800      C 2023-04-28 12:28:02          849446          244   849436             998459         0             N 2023-04-28 12:28:02             0             0
2           771812      C 2023-04-28 12:28:09          849454          183   849436             998460         1             N 2023-04-28 12:28:09             0             0
3           771828      C 2023-04-28 12:28:16          847375          101   849436             998461         0             N 2023-04-28 12:28:16             0             0
4           771851      C 2023-04-28 12:28:26          849477          209   849436             998462         1             N 2023-04-28 12:28:26             0             0
5           771864      C 2023-04-28 12:28:32          849670          239   849436             998463         0             N 2023-04-28 12:28:32             0             0
7           771908      C 2023-04-28 12:28:55          849446          146   849436             998464         0             N 2023-04-28 12:28:55             0             0
10          771940      I 2023-04-28 12:29:13          849634          297   849436             998465         1             N 2023-04-28 12:29:13             0             1
11          771952      C 2023-04-28 12:29:21          849442          294   849436             998466         0             N 2023-04-28 12:29:21             0             0
14          771974      C 2023-04-28 12:29:33          849453          201   849436             998467         0             N 2023-04-28 12:29:33             0             0
97          772499      C 2023-04-28 12:33:38          849445          299   849436             998918         0             N 2023-04-28 12:33:38             0             0
101         772521      C 2023-04-28 12:33:45          849441          248   849436             998919         0             N 2023-04-28 12:33:45             0             0
110         772583      C 2023-04-28 12:34:05          849446          169   849436             998921         0             N 2023-04-28 12:34:05             0             0
122         772665      C 2023-04-28 12:34:29          849488          306   849436             998923         1             N 2023-04-28 12:34:29             0             0
125         772681      C 2023-04-28 12:34:36          849450          223   849436             998924         0             N 2023-04-28 12:34:36             0             0
131         772750      C 2023-04-28 12:34:55          849475          294   849436             998925         0             N 2023-04-28 12:34:55             0             0
143         772875      C 2023-04-28 12:35:24          849488          301   849436             998927         1             N 2023-04-28 12:35:24             0             0
413         779764      C 2023-04-28 13:25:51          849670          279   849436            1000978         0             N 2023-04-28 13:25:51             0             0
417         779820      C 2023-04-28 13:26:19          849450          267   849436            1000979         0             N 2023-04-28 13:26:19             0             0
420         779862      C 2023-04-28 13:26:33          849995          145   849436            1000980         0             N 2023-04-28 13:26:33             0             0
435         780000      C 2023-04-28 13:27:20          849444          256   849436            1000981         0             N 2023-04-28 13:27:20             0             0
442         780065      C 2023-04-28 13:27:37          849452          217   849436            1000982         0             N 2023-04-28 13:27:37             0             0
445         780084      C 2023-04-28 13:27:42          849983          178   849436            1000983         0             N 2023-04-28 13:27:42             0             0
450         780126      C 2023-04-28 13:27:55          849451          244   849436            1000984         0             N 2023-04-28 13:27:55             0             0
461         780211      C 2023-04-28 13:28:18          849762          260   849436            1000985         0             N 2023-04-28 13:28:18             0             0
466         780258      C 2023-04-28 13:28:30          849453          208   849436            1000986         0             N 2023-04-28 13:28:30             0             0
469         780282      C 2023-04-28 13:28:38          849453          316   849436            1000987         0             N 2023-04-28 13:28:38             0             0
931         787990      C 2023-04-28 14:20:32          849446          157   849436            1012638         0             N 2023-04-28 14:20:32             0             0
937         788032      C 2023-04-28 14:20:51          847375          193   849436            1012639         0             N 2023-04-28 14:20:51             0             0
940         788065      C 2023-04-28 14:21:07          849963          310   849436            1012640         0             N 2023-04-28 14:21:07             0             0
944         788098      C 2023-04-28 14:21:18          849441          211   849436            1012641         0             N 2023-04-28 14:21:18             0             0
948         788146      C 2023-04-28 14:21:36          849469          275   849436            1012642         0             N 2023-04-28 14:21:36             0             0
952         788171      C 2023-04-28 14:21:46          849454          168   849436            1012643         1             N 2023-04-28 14:21:46             0             0
955         788215      C 2023-04-28 14:22:09          849439          151   849436            1012644         0             N 2023-04-28 14:22:09             0             0
957         788264      C 2023-04-28 14:22:26          849558          291   849436            1012645         0             N 2023-04-28 14:22:26             0             0
962         788336      C 2023-04-28 14:22:55          849442          325   849436            1012647         0             N 2023-04-28 14:22:55             0             0
1397        796027      C 2023-04-28 15:13:57          850392          174   849436            1024129         0             N 2023-04-28 15:13:57             0             0
1407        796077      C 2023-04-28 15:14:18          850248          272   849436            1024130         0             N 2023-04-28 15:14:18             0             0
1416        796133      C 2023-04-28 15:14:46          849453          246   849436            1024131         0             N 2023-04-28 15:14:46             0             0
1435        796239      C 2023-04-28 15:15:37          849454          262   849436            1024132         1             N 2023-04-28 15:15:37             0             0
1444        796317      C 2023-04-28 15:16:05          849559          226   849436            1024133         0             N 2023-04-28 15:16:05             0             0
1458        796397      C 2023-04-28 15:16:36          849558          195   849436            1024134         0             N 2023-04-28 15:16:36             0             0
1470        796468      C 2023-04-28 15:17:02          849469          209   849436            1024135         0             N 2023-04-28 15:17:02             0             0
1476        796496      C 2023-04-28 15:17:11          839124          312   849436            1024136         0             N 2023-04-28 15:17:11             0             0
1759        801191      C 2023-04-28 15:52:17          847375          122   849436            1035518         0             N 2023-04-28 15:52:17             0             0
1760        801236      C 2023-04-28 15:52:34          849548          178   849436            1035519         1             N 2023-04-28 15:52:34             0             0
1761        801257      C 2023-04-28 15:52:43          849995          304   849436            1035520         0             N 2023-04-28 15:52:43             0             0
1762        801279      C 2023-04-28 15:52:52          849528          152   849436            1035521         0             N 2023-04-28 15:52:52             0             0
1763        801293      C 2023-04-28 15:52:59          849450          310   849436            1035522         0             N 2023-04-28 15:52:59             0             0
1766        801334      C 2023-04-28 15:53:18          849559          126   849436            1035523         0             N 2023-04-28 15:53:18             0             0
1768        801369      C 2023-04-28 15:53:33          849442          289   849436            1035524         0             N 2023-04-28 15:53:33             0             0
1774        801486      C 2023-04-28 15:54:23          850217           99   849436            1035525         0             N 2023-04-28 15:54:23             0             0
1776        801541      C 2023-04-28 15:54:45          850392          285   849436            1035527         0             N 2023-04-28 15:54:45             0             0
2202        806958      I 2023-04-28 16:47:58          849559          214   849436            1042148         0             N 2023-04-28 16:47:58             0             1
2211        807112      C 2023-04-28 16:49:13          850229          274   849436            1042151         0             N 2023-04-28 16:49:13             0             0
2216        807172      C 2023-04-28 16:49:44          850269          264   849436            1042152         1             N 2023-04-28 16:49:44             0             0
2217        807180      C 2023-04-28 16:49:53          847375          308   849436            1042153         0             N 2023-04-28 16:49:53             0             0
2219        807195      C 2023-04-28 16:50:06          849441          323   849436            1042154         0             N 2023-04-28 16:50:06             0             0
2226        807235      I 2023-04-28 16:50:36          849634          158   849436            1042155         1             N 2023-04-28 16:50:36             0             1
2228        807256      C 2023-04-28 16:50:50          849455          117   849436            1042156         0             N 2023-04-28 16:50:50             0             0
2231        807269      C 2023-04-28 16:51:02          849488          283   849436            1042157         1             N 2023-04-28 16:51:02             0             0
2526        810070      C 2023-04-28 17:41:20          847375          183   849436            1049708         0             N 2023-04-28 17:41:20             0             0
2530        810088      C 2023-04-28 17:41:29          849446          136   849436            1049709         0             N 2023-04-28 17:41:29             0             0
2536        810116      C 2023-04-28 17:41:46          849469          319   849436            1049710         0             N 2023-04-28 17:41:46             0             0
2543        810195      C 2023-04-28 17:42:49          849453          322   849436            1049711         0             N 2023-04-28 17:42:49             0             0
2544        810205      C 2023-04-28 17:42:59          850728          271   849436            1049712         0             N 2023-04-28 17:42:59             0             0
2547        810234      C 2023-04-28 17:43:30          849489          150   849436            1049713         0             N 2023-04-28 17:43:30             0             0
2548        810244      C 2023-04-28 17:43:43          849438          105   849436            1049714         0             N 2023-04-28 17:43:43             0             0
2549        810248      C 2023-04-28 17:43:52          849559          212   849436            1049715         0             N 2023-04-28 17:43:52             0             0
2552        810261      C 2023-04-28 17:44:10          849498          135   849436            1049716         0             N 2023-04-28 17:44:10             0             0
2555        810269      C 2023-04-28 17:44:23          849452          163   849436            1049717         0             N 2023-04-28 17:44:23             0             0
2737        811892      C 2023-04-28 18:40:57          849489          215   849436            1053658         0             N 2023-04-28 18:40:57             0             0
2738        811898      C 2023-04-28 18:41:07          850574          285   849436            1053659         0             N 2023-04-28 18:41:07             0             0
2739        811921      C 2023-04-28 18:41:48          849488          178   849436            1053661         1             N 2023-04-28 18:41:48             0             0
2740        811929      C 2023-04-28 18:41:58          850161          117   849436            1053662         0             N 2023-04-28 18:41:58             0             0
2741        811944      C 2023-04-28 18:42:14          850161          251   849436            1053663         0             N 2023-04-28 18:42:14             0             0
2742        811958      C 2023-04-28 18:42:36          849497          291   849436            1053664         0             N 2023-04-28 18:42:36             0             0
2743        811963      C 2023-04-28 18:42:45          849559          182   849436            1053665         0             N 2023-04-28 18:42:45             0             0
2744        811970      C 2023-04-28 18:42:57          849438          279   849436            1053666         0             N 2023-04-28 18:42:57             0             0
2745        811975      C 2023-04-28 18:43:17          847375          237   849436            1053667         0             N 2023-04-28 18:43:17             0             0
2870        812846      C 2023-04-28 19:44:35          849558          314   849436            1055788         0             N 2023-04-28 19:44:35             0             0
2871        812847      C 2023-04-28 19:44:48          849450          301   849436            1055789         0             N 2023-04-28 19:44:48             0             0
2872        812853      C 2023-04-28 19:45:14          849454          311   849436            1055790         1             N 2023-04-28 19:45:14             0             0
2873        812857      C 2023-04-28 19:45:27          849439          236   849436            1055791         0             N 2023-04-28 19:45:27             0             0
2874        812858      C 2023-04-28 19:45:37          849446          108   849436            1055792         0             N 2023-04-28 19:45:37             0             0
2875        812861      C 2023-04-28 19:45:53          849995          137   849436            1055793         0             N 2023-04-28 19:45:53             0             0
2876        812865      C 2023-04-28 19:46:11          849983          126   849436            1055795         0             N 2023-04-28 19:46:11             0             0
2877        812868      C 2023-04-28 19:46:26          849469          170   849436            1055796         0             N 2023-04-28 19:46:26             0             0
2878        812869      C 2023-04-28 19:46:38          850217          267   849436            1055797         0             N 2023-04-28 19:46:38             0             0
3168        817067      C 2023-04-28 23:59:08          849634          178   849436            1056899         1             N 2023-04-28 23:59:08             0             0
3169        817081      C 2023-04-28 23:59:18          849450          152   849436            1056900         0             N 2023-04-28 23:59:18             0             0
3170        817097      C 2023-04-28 23:59:34          850229          164   849436            1056901         0             N 2023-04-28 23:59:34             0             0
3171        817106      C 2023-04-28 23:59:47          849442          312   849436            1056902         0             N 2023-04-28 23:59:47             0             0
3175        817141      C 2023-04-29 00:00:21          849489          237   849436            1056903         0             N 2023-04-29 00:00:21             0             0
3178        817162      C 2023-04-29 00:00:38          850217          264   849436            1056904         0             N 2023-04-29 00:00:38             0             0
3180        817173      C 2023-04-29 00:00:49          850161          235   849436            1056905         0             N 2023-04-29 00:00:49             0             0
3184        817229      C 2023-04-29 00:01:33          850077          282   849436            1056906         0             N 2023-04-29 00:01:33             0             0
3185        817249      C 2023-04-29 00:01:51          849441          211   849436            1056907         0             N 2023-04-29 00:01:51             0             0
3767        826279      C 2023-04-29 01:55:33          849548          264   849436            1062448         1             N 2023-04-29 01:55:33             0             0
3768        826294      C 2023-04-29 01:55:44          849946          168   849436            1062449         0             N 2023-04-29 01:55:44             0             0
3769        826300      C 2023-04-29 01:55:50          850319          317   849436            1062450         0             N 2023-04-29 01:55:50             0             0
3770        826311      C 2023-04-29 01:55:58          849454          253   849436            1062451         1             N 2023-04-29 01:55:58             0             0
3771        826323      C 2023-04-29 01:56:05          850574          251   849436            1062452         0             N 2023-04-29 01:56:05             0             0
3773        826334      C 2023-04-29 01:56:13          849441          273   849436            1062453         0             N 2023-04-29 01:56:13             0             0
3775        826342      C 2023-04-29 01:56:22          849446          320   849436            1062454         0             N 2023-04-29 01:56:22             0             0
3777        826349      C 2023-04-29 01:56:30          849623          299   849436            1062455         0             N 2023-04-29 01:56:30             0             0
3779        826354      C 2023-04-29 01:56:38          849469          155   849436            1062456         0             N 2023-04-29 01:56:38             0             0
3784        826366      C 2023-04-29 01:56:48          849446          226   849436            1062457         0             N 2023-04-29 01:56:48             0             0
4173        832246      C 2023-04-29 02:49:55          849441          104   849436            1073778         0             N 2023-04-29 02:49:55             0             0
4175        832259      C 2023-04-29 02:50:03          850161          122   849436            1073779         0             N 2023-04-29 02:50:03             0             0
4181        832339      C 2023-04-29 02:50:43          849489          274   849436            1073781         0             N 2023-04-29 02:50:43             0             0
4182        832357      C 2023-04-29 02:50:53          839124          279   849436            1073782         0             N 2023-04-29 02:50:53             0             0
4185        832430      C 2023-04-29 02:51:33          849439          238   849436            1073784         0             N 2023-04-29 02:51:33             0             0

In [15]:
polls_questionpiece.head(30)

        id  is_voted          created_at  question_id  is_skipped
0   998458         1 2023-04-28 12:27:22          252           0
1   998459         1 2023-04-28 12:27:22          244           0
2   998460         1 2023-04-28 12:27:22          183           0
3   998461         1 2023-04-28 12:27:22          101           0
4   998462         1 2023-04-28 12:27:22          209           0
5   998463         1 2023-04-28 12:27:22          239           0
6   998464         1 2023-04-28 12:27:22          146           0
7   998465         1 2023-04-28 12:27:22          297           0
8   998466         1 2023-04-28 12:27:22          294           0
9   998467         1 2023-04-28 12:27:22          201           0
10  998588         1 2023-04-28 12:28:07          237           0
11  998589         1 2023-04-28 12:28:07          138           0
12  998590         1 2023-04-28 12:28:07          184           0
13  998591         1 2023-04-28 12:28:07          157           0
14  998592         1 2023-04-28 12:28:07          276           0
15  998593         1 2023-04-28 12:28:07          135           0
16  998594         1 2023-04-28 12:28:07          257           0
17  998595         1 2023-04-28 12:28:07          280           0
18  998597         1 2023-04-28 12:28:07          251           0
19  998689         1 2023-04-28 12:28:38          247           0
20  998691         1 2023-04-28 12:28:38          228           0
21  998693         1 2023-04-28 12:28:38          188           0
22  998694         1 2023-04-28 12:28:38          205           0
23  998695         1 2023-04-28 12:28:38          133           0
24  998696         1 2023-04-28 12:28:38          251           0
25  998697         1 2023-04-28 12:28:38          152           0
26  998699         1 2023-04-28 12:28:38          312           0
27  998700         1 2023-04-28 12:28:38           99           0
28  998701         1 2023-04-28 12:28:38          189           0
29  998702         1 2023-04-28 12:28:38          261           0

In [16]:
polls_questionpiece.id.nunique()

1265476

In [17]:
# polls_questionpiece csv 파일로 다운로드
polls_questionpiece.to_csv('polls_questionpiece.csv', index=False)

In [18]:
# created_at을 datetime으로 변환 (만약 아직 문자열이면)
polls_questionpiece['created_at'] = pd.to_datetime(polls_questionpiece['created_at'])

# 조건 필터링
filtered_df = polls_questionpiece[
    (polls_questionpiece['question_id'] == 119) &
    (polls_questionpiece['created_at'] >= '2023-04-28 13:10:00') &
    (polls_questionpiece['created_at'] <= '2023-04-28 14:00:00')
]

# 결과 확인
print(filtered_df)

           id  is_voted          created_at  question_id  is_skipped
709   1009127         1 2023-04-28 13:11:02          119           0
710   1009132         1 2023-04-28 13:11:02          119           0
873   1012290         1 2023-04-28 13:27:23          119           0
940   1013081         1 2023-04-28 13:30:03          119           0
1017  1013856         1 2023-04-28 13:34:00          119           0
1238  1018228         1 2023-04-28 13:54:32          119           0
1324  1019466         1 2023-04-28 13:59:05          119           0

In [19]:
polls_questionpiece.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1265476 entries, 0 to 1265475
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1265476 non-null  int64
 1   is_voted     1265476 non-null  int64
 2   created_at   1265476 non-null  datetime64[ns]
 3   question_id  1265476 non-null  int64
 4   is_skipped   1265476 non-null  int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 48.3 MB

In [20]:
# 조건에 맞는 행 필터링
unprocessed_df = polls_questionpiece[
    (polls_questionpiece['is_voted'] == 0) & 
    (polls_questionpiece['is_skipped'] == 0)
]

# 결과 확인
unprocessed_df.head()

           id  is_voted          created_at  question_id  is_skipped
1084  1015518         0 2023-04-28 13:41:27          268           0
1085  1015519         0 2023-04-28 13:41:27          184           0
1086  1015520         0 2023-04-28 13:41:27          141           0
1087  1015521         0 2023-04-28 13:41:27          172           0
1088  1015522         0 2023-04-28 13:41:27          259           0

In [21]:
unprocessed_df.head(20)

           id  is_voted          created_at  question_id  is_skipped
1084  1015518         0 2023-04-28 13:41:27          268           0
1085  1015519         0 2023-04-28 13:41:27          184           0
1086  1015520         0 2023-04-28 13:41:27          141           0
1087  1015521         0 2023-04-28 13:41:27          172           0
1088  1015522         0 2023-04-28 13:41:27          259           0
1089  1015523         0 2023-04-28 13:41:27          321           0
1090  1015524         0 2023-04-28 13:41:27          196           0
1091  1015525         0 2023-04-28 13:41:27          127           0
1092  1015526         0 2023-04-28 13:41:27          293           0
1093  1015527         0 2023-04-28 13:41:27          317           0
1599  1023569         0 2023-04-28 14:19:21          303           0
1600  1023570         0 2023-04-28 14:19:21          214           0
1601  1023571         0 2023-04-28 14:19:21          234           0
1602  1023572         0 2023-04-28 14:19:21          191           0
1603  1023573         0 2023-04-28 14:19:21          321           0
1604  1023574         0 2023-04-28 14:19:21          144           0
1605  1023575         0 2023-04-28 14:19:21          153           0
1606  1023576         0 2023-04-28 14:19:21          156           0
1607  1023577         0 2023-04-28 14:19:21          112           0
6237  1098618         0 2023-04-29 04:43:25          221           0

In [22]:
# 2023-04-28 14:19:21
unprocessed_df[unprocessed_df['created_at'] == '2023-04-28 14:19:21']

           id  is_voted          created_at  question_id  is_skipped
1599  1023569         0 2023-04-28 14:19:21          303           0
1600  1023570         0 2023-04-28 14:19:21          214           0
1601  1023571         0 2023-04-28 14:19:21          234           0
1602  1023572         0 2023-04-28 14:19:21          191           0
1603  1023573         0 2023-04-28 14:19:21          321           0
1604  1023574         0 2023-04-28 14:19:21          144           0
1605  1023575         0 2023-04-28 14:19:21          153           0
1606  1023576         0 2023-04-28 14:19:21          156           0
1607  1023577         0 2023-04-28 14:19:21          112           0

In [23]:
unprocessed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46789 entries, 1084 to 1265475
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           46789 non-null  int64
 1   is_voted     46789 non-null  int64
 2   created_at   46789 non-null  datetime64[ns]
 3   question_id  46789 non-null  int64
 4   is_skipped   46789 non-null  int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 2.1 MB

In [24]:
# is_voted == 0 and is_skipped == 0인 행 기준으로 그룹
created_at_counts = unprocessed_df['created_at'].value_counts().sort_index()

# 결과 출력
print(created_at_counts)

created_at
2023-04-28 13:41:27    10
2023-04-28 14:19:21     9
2023-04-29 04:43:25    10
2023-04-29 13:28:26    10
2023-04-29 13:59:53     6
2023-04-29 13:59:54     4
2023-04-29 16:50:41    10
2023-04-30 04:43:54    10
2023-04-30 05:33:39    10
2023-04-30 09:39:13     7
2023-04-30 10:36:28    10
2023-04-30 14:10:34    10
2023-04-30 14:49:42    10
2023-04-30 15:04:16     7
2023-04-30 15:38:28    10
2023-04-30 16:17:37    10
2023-05-01 04:20:12    10
2023-05-01 07:08:59    10
2023-05-01 11:47:20    10
2023-05-01 11:55:03    10
2023-05-02 05:17:11     6
2023-05-02 06:55:40    10
2023-05-02 10:25:07    10
2023-05-02 11:19:30    10
2023-05-02 12:09:44    10
2023-05-02 14:01:02    10
2023-05-02 14:58:00     9
2023-05-02 15:57:09    10
2023-05-02 16:40:58    10
2023-05-02 18:32:29     9
2023-05-02 22:37:05     3
2023-05-02 23:26:30     8
2023-05-03 00:39:04     9
2023-05-03 04:09:44     4
2023-05-03 06:32:19    10
2023-05-03 08:03:53    10
2023-05-03 09:15:31     6
2023-05-03 09:24:14    10
2023-05-03 09:28:58    10
2023-05-03 09:29:26    10
2023-05-03 09:50:44     6
2023-05-03 10:21:27    10
2023-05-03 12:23:11     6
2023-05-03 12:23:46     9
2023-05-03 13:11:58    10
2023-05-03 13:27:11     6
2023-05-03 13:27:12     4
2023-05-03 13:28:24    10
2023-05-03 14:41:20     8
2023-05-03 15:03:37     6
2023-05-03 15:38:21    10
2023-05-03 16:14:07    10
2023-05-03 16:54:47     7
2023-05-03 16:54:48     3
2023-05-03 22:54:03     5
2023-05-03 23:15:53    10
2023-05-04 01:40:18     5
2023-05-04 01:52:08    10
2023-05-04 03:19:03    10
2023-05-04 04:53:17    10
2023-05-04 06:41:27    10
2023-05-04 07:21:43     1
2023-05-04 07:26:27    10
2023-05-04 07:48:01    10
2023-05-04 08:26:36    10
2023-05-04 09:01:57    10
2023-05-04 11:45:12    10
2023-05-04 11:58:15     6
2023-05-04 12:19:48    10
2023-05-04 12:23:04     2
2023-05-04 12:42:39     7
2023-05-04 13:07:28    10
2023-05-04 13:26:14    10
2023-05-04 13:40:14    10
2023-05-04 14:06:50    10
2023-05-04 14:40:18     6
2023-05-04 14:40:19     1
2023-05-04 14:47:34    10
2023-05-04 15:09:18    10
2023-05-04 15:22:20     9
2023-05-04 15:22:21     1
2023-05-04 15:27:31     4
2023-05-04 15:44:42    10
2023-05-04 16:25:24     9
2023-05-04 16:29:35    10
2023-05-04 16:34:09    10
2023-05-05 02:23:25    10
2023-05-05 03:34:23    10
2023-05-05 03:48:02     1
2023-05-05 03:48:03     9
2023-05-05 05:03:17    10
2023-05-05 05:11:31     6
2023-05-05 05:35:01     9
2023-05-05 06:45:44    10
2023-05-05 07:52:06     9
2023-05-05 08:07:27    10
2023-05-05 08:51:06    10
2023-05-05 09:30:38    10
2023-05-05 09:32:15    10
2023-05-05 10:18:15    10
2023-05-05 10:22:34    10
2023-05-05 11:17:29    10
2023-05-05 12:27:36     7
2023-05-05 12:43:53     5
2023-05-05 13:16:04     7
2023-05-05 13:22:00     7
2023-05-05 13:27:23    10
2023-05-05 13:33:17    10
2023-05-05 13:38:12     7
2023-05-05 13:43:17    10
2023-05-05 13:49:27    10
2023-05-05 13:59:55     5
2023-05-05 14:13:23    10
2023-05-05 14:24:59    10
2023-05-05 14:38:39     7
2023-05-05 15:00:43    10
2023-05-05 15:04:27    10
2023-05-05 15:11:07     7
2023-05-05 15:11:08     3
2023-05-05 15:29:33    10
2023-05-05 15:42:17    10
2023-05-05 15:55:59     8
2023-05-05 15:56:00     2
2023-05-05 16:02:21    10
2023-05-05 16:03:54    10
2023-05-05 16:11:30    10
2023-05-05 16:13:21    10
2023-05-05 16:40:40     7
2023-05-05 16:40:41     3
2023-05-05 16:55:21    10
2023-05-05 17:04:52    10
2023-05-05 17:55:49    10
2023-05-06 00:45:57    10
2023-05-06 03:05:47    10
2023-05-06 03:06:49    10
2023-05-06 03:18:27    10
2023-05-06 03:21:21     7
2023-05-06 03:21:22     3
2023-05-06 03:42:21    10
2023-05-06 03:49:27    10
2023-05-06 03:49:55    10
2023-05-06 04:12:37     4
2023-05-06 04:14:50    10
2023-05-06 05:38:25     9
2023-05-06 05:43:00    10
2023-05-06 05:47:26     2
2023-05-06 05:51:54    10
2023-05-06 06:18:09    10
2023-05-06 06:27:56     6
2023-05-06 06:43:26    10
2023-05-06 07:47:16    10
2023-05-06 07:57:45    10
2023-05-06 08:08:30    10
2023-05-06 08:09:49     6
2023-05-06 08:37:37    10
2023-05-06 08:43:05    10
2023-05-06 08:49:36     4
2023-05-06 08:55:23    10
2023-05-06 08:57:57    10
2023-05-06 09:33:53    10
2023-05-06 09:51:39    10
2023-05-06 10:13:44     9
2023-05-06 10:28:11    10
2023-05-06 10:30:16    10
2023-05-06 10:36:05     7
2023-05-06 11:07:56     2
2023-05-06 11:42:51    10
2023-05-06 11:56:09    10
2023-05-06 12:23:33    10
2023-05-06 12:48:03    10
2023-05-06 13:06:37    10
2023-05-06 13:30:22    10
2023-05-06 14:03:26     7
2023-05-06 14:24:06     6
2023-05-06 15:05:54    10
2023-05-06 15:47:37    10
2023-05-06 15:53:28    10
2023-05-06 16:23:45    10
2023-05-06 16:31:53    10
2023-05-06 16:40:36     9
2023-05-06 16:53:26    10
2023-05-06 16:59:21    10
2023-05-06 17:41:45    10
2023-05-06 18:34:53    10
2023-05-06 20:05:38    10
2023-05-06 22:17:30     5
2023-05-06 22:26:53     9
2023-05-06 22:58:54    10
2023-05-06 23:33:29    10
2023-05-06 23:52:13     8
2023-05-07 00:53:50    10
2023-05-07 01:51:45    10
2023-05-07 02:48:43     3
2023-05-07 02:54:47     6
2023-05-07 03:14:35    10
2023-05-07 04:06:42    10
2023-05-07 04:08:19    10
2023-05-07 04:14:12    10
2023-05-07 04:27:11    10
2023-05-07 04:39:10    10
2023-05-07 05:22:13    10
2023-05-07 05:57:35     5
2023-05-07 06:31:29    10
2023-05-07 06:51:06    10
2023-05-07 07:06:02    10
2023-05-07 07:07:18    10
2023-05-07 07:08:50     6
2023-05-07 07:16:12    10
2023-05-07 07:17:20     7
2023-05-07 07:34:23    10
2023-05-07 09:30:32     6
2023-05-07 09:32:02     1
2023-05-07 09:32:03     5
2023-05-07 09:33:02     8
2023-05-07 10:24:18     3
2023-05-07 10:24:19     7
2023-05-07 10:30:11    10
2023-05-07 10:41:57     9
2023-05-07 10:44:05    10
2023-05-07 10:50:10    10
2023-05-07 11:21:14    10
2023-05-07 11:28:35    10
2023-05-07 11:41:06     8
2023-05-07 11:57:34     7
2023-05-07 11:57:35     3
2023-05-07 11:58:09    10
2023-05-07 12:08:49    10
2023-05-07 12:20:43    10
2023-05-07 12:25:10    10
2023-05-07 12:45:44     4
2023-05-07 12:45:54    10
2023-05-07 12:51:41    10
2023-05-07 12:54:23    10
2023-05-07 12:59:05     8
2023-05-07 12:59:06     2
2023-05-07 13:01:51    10
2023-05-07 13:08:30    10
2023-05-07 13:17:52    10
2023-05-07 13:27:14    10
2023-05-07 13:28:32    10
2023-05-07 13:30:23    10
2023-05-07 13:38:22     2
2023-05-07 13:38:23     8
2023-05-07 13:55:08     5
2023-05-07 13:55:09     5
2023-05-07 13:58:28    10
2023-05-07 14:05:16     7
2023-05-07 14:05:17     3
2023-05-07 14:05:31     3
2023-05-07 14:05:32     7
2023-05-07 14:07:24    10
2023-05-07 14:08:27    10
2023-05-07 14:09:52    10
2023-05-07 14:13:10    10
2023-05-07 14:17:30    10
2023-05-07 14:27:13    10
2023-05-07 14:36:49    10
2023-05-07 14:41:01    10
2023-05-07 14:46:15    10
2023-05-07 14:57:03     5
2023-05-07 15:01:56    10
2023-05-07 15:02:59     4
2023-05-07 15:23:48    10
2023-05-07 15:34:30    10
2023-05-07 15:46:36    10
2023-05-07 15:46:46    10
2023-05-07 15:59:49    10
2023-05-07 16:11:38    10
2023-05-07 17:14:11    10
2023-05-07 17:25:38    10
2023-05-07 18:22:37    10
2023-05-07 22:18:43    10
2023-05-07 22:20:35    10
2023-05-08 00:07:05     5
2023-05-08 00:07:06     5
2023-05-08 00:09:54     8
2023-05-08 00:11:36    10
2023-05-08 00:12:51    10
2023-05-08 00:17:56    10
2023-05-08 00:19:20    10
2023-05-08 00:28:19     8
2023-05-08 00:36:16     5
2023-05-08 00:44:28     4
2023-05-08 00:44:29     3
2023-05-08 01:20:55    10
2023-05-08 02:06:42    10
2023-05-08 02:52:24    10
2023-05-08 02:55:16    10
2023-05-08 02:58:48    10
2023-05-08 03:20:41     9
2023-05-08 03:34:00    10
2023-05-08 03:34:17    10
2023-05-08 03:49:58    10
2023-05-08 04:32:13     7
2023-05-08 05:27:53    10
2023-05-08 05:37:31     7
2023-05-08 05:37:32     3
2023-05-08 05:41:53    10
2023-05-08 05:46:11    10
2023-05-08 05:59:02    10
2023-05-08 06:02:21     9
2023-05-08 06:08:54    10
2023-05-08 06:11:18    10
2023-05-08 06:12:11    10
2023-05-08 06:19:55    10
2023-05-08 06:34:09    10
2023-05-08 06:39:54    10
2023-05-08 07:18:48    10
2023-05-08 07:34:40     5
2023-05-08 07:50:09    10
2023-05-08 07:52:26     2
2023-05-08 07:52:27     8
2023-05-08 08:43:15    10
2023-05-08 08:56:28     8
2023-05-08 09:14:53    10
2023-05-08 09:28:28    10
2023-05-08 09:34:09    10
2023-05-08 10:06:15     9
2023-05-08 10:06:16     1
2023-05-08 10:08:56    10
2023-05-08 10:17:55    10
2023-05-08 10:21:18    10
2023-05-08 10:45:06    10
2023-05-08 11:06:42    10
2023-05-08 11:25:05     9
2023-05-08 11:25:06     1
2023-05-08 11:25:26    10
2023-05-08 11:41:58    10
2023-05-08 12:01:09    10
2023-05-08 12:12:56     1
2023-05-08 12:15:16    19
2023-05-08 12:21:30    10
2023-05-08 12:34:37    10
2023-05-08 12:39:10    10
2023-05-08 12:54:56    10
2023-05-08 13:14:01    10
2023-05-08 13:19:38    10
2023-05-08 13:22:47     9
2023-05-08 13:22:48     1
2023-05-08 13:48:29    10
2023-05-08 14:03:49     5
2023-05-08 14:04:49    10
2023-05-08 14:06:21    10
2023-05-08 14:07:52    10
2023-05-08 14:19:43    10
2023-05-08 14:20:07    10
2023-05-08 14:43:07    10
2023-05-08 14:49:37     3
2023-05-08 14:49:38     7
2023-05-08 14:53:27     3
2023-05-08 14:53:28     7
2023-05-08 15:04:34     8
2023-05-08 15:13:56    10
2023-05-08 15:42:15    10
2023-05-08 16:00:13    10
2023-05-08 16:06:56     9
2023-05-08 16:26:42    10
2023-05-08 16:34:26    10
2023-05-08 16:34:41    10
2023-05-08 16:39:00    10
2023-05-08 16:48:32    10
2023-05-08 16:55:42    10
2023-05-08 17:38:25    10
2023-05-08 17:54:22    10
2023-05-08 18:38:41     9
2023-05-08 18:38:42     1
2023-05-08 21:57:50     2
2023-05-08 22:23:42    10
2023-05-08 22:48:09    10
2023-05-08 23:31:45    10
2023-05-09 00:03:00     5
2023-05-09 00:03:01     5
2023-05-09 00:28:40    10
2023-05-09 00:53:20    10
2023-05-09 01:03:52     7
2023-05-09 01:04:32     8
2023-05-09 01:08:27    10
2023-05-09 01:26:14    10
2023-05-09 01:57:20    10
2023-05-09 02:08:31    10
2023-05-09 02:12:29    10
2023-05-09 02:20:15     9
2023-05-09 02:20:16     1
2023-05-09 02:27:36     5
2023-05-09 02:27:37     5
2023-05-09 02:27:47     7
2023-05-09 02:27:48     3
2023-05-09 02:38:54    10
2023-05-09 02:41:04    10
2023-05-09 02:51:59    10
2023-05-09 03:16:18    10
2023-05-09 03:48:59     7
2023-05-09 03:54:23    10
2023-05-09 04:11:24    10
2023-05-09 05:17:56    10
2023-05-09 05:18:34    10
2023-05-09 05:32:18    10
2023-05-09 06:08:52    10
2023-05-09 06:34:45    10
2023-05-09 07:02:53    10
2023-05-09 07:25:32    10
2023-05-09 07:52:45     8
2023-05-09 08:28:06    10
2023-05-09 08:35:12    10
2023-05-09 08:54:44     7
2023-05-09 09:13:19    10
2023-05-09 09:13:59    10
2023-05-09 09:19:08    10
2023-05-09 09:37:54    10
2023-05-09 09:39:48    10
2023-05-09 09:45:46    10
2023-05-09 09:50:15    10
2023-05-09 10:08:01     6
2023-05-09 10:18:23     4
2023-05-09 10:35:39    10
2023-05-09 10:40:20     8
2023-05-09 10:43:49    10
2023-05-09 10:53:34    10
2023-05-09 10:55:03    10
2023-05-09 11:09:44     6
2023-05-09 11:09:45     4
2023-05-09 11:11:32    10
2023-05-09 11:29:16    10
2023-05-09 11:33:33    10
2023-05-09 11:37:22    10
2023-05-09 11:40:40    10
2023-05-09 11:43:15     6
2023-05-09 11:43:16     2
2023-05-09 11:45:22    10
2023-05-09 12:34:41    10
2023-05-09 12:42:53    10
2023-05-09 13:28:43    10
2023-05-09 13:36:57    10
2023-05-09 13:41:20    10
2023-05-09 13:57:14    10
2023-05-09 14:01:21    10
2023-05-09 14:08:42    10
2023-05-09 14:43:05    10
2023-05-09 15:14:11    10
2023-05-09 15:22:52    10
2023-05-09 15:26:05    10
2023-05-09 15:27:02     9
2023-05-09 15:27:03     1
2023-05-09 15:27:45     7
2023-05-09 15:27:46     3
2023-05-09 15:35:26     9
2023-05-09 15:46:14    10
2023-05-09 15:47:15    10
2023-05-09 15:49:38     7
2023-05-09 15:52:13     4
2023-05-09 15:52:14     6
2023-05-09 16:06:24    10
2023-05-09 16:11:27    10
2023-05-09 16:13:36    10
2023-05-09 16:16:51     7
2023-05-09 16:16:52     3
2023-05-09 16:26:13    10
2023-05-09 16:31:32    10
2023-05-09 16:51:08    10
2023-05-09 21:14:36    10
2023-05-09 22:41:42    10
2023-05-09 22:48:56    10
2023-05-09 23:17:20    10
2023-05-09 23:21:20    10
2023-05-09 23:30:47     9
2023-05-09 23:32:16    10
2023-05-09 23:43:42    10
2023-05-10 00:17:04    10
2023-05-10 00:24:33    10
2023-05-10 00:25:36    10
2023-05-10 01:41:54    10
2023-05-10 01:42:50    10
2023-05-10 01:47:21    10
2023-05-10 02:13:20    10
2023-05-10 02:20:52    10
2023-05-10 02:28:24    10
2023-05-10 02:40:36    10
2023-05-10 02:41:47    10
2023-05-10 02:42:45     9
2023-05-10 02:42:48     3
2023-05-10 03:11:17    10
2023-05-10 03:21:56    10
2023-05-10 03:22:48    10
2023-05-10 03:52:34    10
2023-05-10 04:29:56     7
2023-05-10 04:29:57     3
2023-05-10 04:34:14    10
2023-05-10 04:34:52    10
2023-05-10 04:42:21    10
2023-05-10 04:52:39    10
2023-05-10 06:20:08     6
2023-05-10 06:51:01    10
2023-05-10 06:53:49     7
2023-05-10 06:54:55    10
2023-05-10 07:28:37     4
2023-05-10 07:50:48    10
2023-05-10 07:58:31    10
2023-05-10 08:17:15    10
2023-05-10 08:23:02    10
2023-05-10 08:41:23    10
2023-05-10 09:10:05    10
2023-05-10 09:14:08    10
2023-05-10 09:25:37    10
2023-05-10 09:56:45    10
2023-05-10 11:00:20     8
2023-05-10 11:00:21     2
2023-05-10 11:01:02    10
2023-05-10 11:27:41     2
2023-05-10 11:31:26     7
2023-05-10 12:22:59    10
2023-05-10 12:26:14    10
2023-05-10 12:26:29    10
2023-05-10 12:29:17    10
2023-05-10 13:03:18    10
2023-05-10 13:09:48    10
2023-05-10 13:24:43    10
2023-05-10 13:36:23    10
2023-05-10 14:00:21     7
2023-05-10 14:00:57    10
2023-05-10 14:04:23    10
2023-05-10 14:06:18    10
2023-05-10 14:06:42     3
2023-05-10 14:06:43     7
2023-05-10 14:53:25    10
2023-05-10 15:21:41     1
2023-05-10 15:26:02    10
2023-05-10 15:31:50     7
2023-05-10 15:52:14    10
2023-05-10 15:55:29     8
2023-05-10 16:41:09    10
2023-05-10 16:43:20    10
2023-05-10 22:48:34    10
2023-05-10 22:52:20    10
2023-05-10 23:11:47    10
2023-05-10 23:49:07     9
2023-05-10 23:56:10    10
2023-05-10 23:58:11     1
2023-05-10 23:58:12     9
2023-05-11 00:03:19     7
2023-05-11 00:31:08    10
2023-05-11 01:13:02    10
2023-05-11 01:13:15    10
2023-05-11 01:29:37    10
2023-05-11 01:36:00     6
2023-05-11 01:36:01     4
2023-05-11 01:38:51    10
2023-05-11 02:15:39     3
2023-05-11 02:16:05    10
2023-05-11 02:29:30    10
2023-05-11 02:53:43    10
2023-05-11 02:56:23     9
2023-05-11 02:56:24     1
2023-05-11 03:00:05    10
2023-05-11 03:05:21    10
2023-05-11 03:06:31     5
2023-05-11 03:06:32     5
2023-05-11 03:13:02     9
2023-05-11 03:13:32     3
2023-05-11 03:13:33     7
2023-05-11 03:14:33    10
2023-05-11 03:20:32    10
2023-05-11 03:34:58    10
2023-05-11 03:36:16    10
2023-05-11 04:04:35    10
2023-05-11 04:33:50    10
2023-05-11 04:49:10    10
2023-05-11 05:13:24    10
2023-05-11 05:53:38     3
2023-05-11 05:53:39     7
2023-05-11 06:02:17    10
2023-05-11 06:24:43     5
2023-05-11 07:29:40    10
2023-05-11 08:01:05    10
2023-05-11 08:04:59    10
2023-05-11 08:05:27    10
2023-05-11 08:06:23    10
2023-05-11 08:51:58    10
2023-05-11 08:59:14    10
2023-05-11 09:01:32     3
2023-05-11 09:08:28    10
2023-05-11 10:19:52    10
2023-05-11 10:58:21     8
2023-05-11 11:17:38    10
2023-05-11 11:33:36    10
2023-05-11 11:39:29    10
2023-05-11 11:54:34    10
2023-05-11 11:55:53    10
2023-05-11 11:56:22    10
2023-05-11 11:57:21    10
2023-05-11 12:00:08    10
2023-05-11 12:19:09    10
2023-05-11 12:31:07    10
2023-05-11 12:47:07    10
2023-05-11 12:47:56    10
2023-05-11 12:56:22     5
2023-05-11 13:10:27     4
2023-05-11 13:10:28     6
2023-05-11 13:15:26    10
2023-05-11 13:44:46    10
2023-05-11 14:14:37    10
2023-05-11 14:16:31    10
2023-05-11 14:22:28    10
2023-05-11 14:25:36    10
2023-05-11 14:48:47    10
2023-05-11 14:52:21    10
2023-05-11 14:55:28    10
2023-05-11 15:06:59     4
2023-05-11 15:14:34    10
2023-05-11 15:16:37    10
2023-05-11 15:20:19     9
2023-05-11 15:27:57    10
2023-05-11 15:50:14    10
2023-05-11 15:52:43     9
2023-05-11 16:14:59    10
2023-05-11 16:32:29     8
2023-05-11 16:56:52    10
2023-05-11 17:14:31    10
2023-05-11 22:17:55    10
2023-05-11 22:18:46    10
2023-05-11 22:27:52     8
2023-05-11 22:53:17    10
2023-05-11 23:01:28     7
2023-05-11 23:22:59    10
2023-05-11 23:47:06     9
2023-05-12 00:14:01    10
2023-05-12 00:20:01    10
2023-05-12 00:31:27    10
2023-05-12 02:49:42    10
2023-05-12 02:51:04    10
2023-05-12 03:26:02    10
2023-05-12 04:35:36    10
2023-05-12 04:44:51    10
2023-05-12 04:47:19    10
2023-05-12 04:48:00    10
2023-05-12 05:07:07    10
2023-05-12 05:17:43    10
2023-05-12 05:49:14     7
2023-05-12 05:58:21    10
2023-05-12 06:35:15    10
2023-05-12 06:54:47    10
2023-05-12 06:59:03     8
2023-05-12 07:41:25     6
2023-05-12 08:30:22    10
2023-05-12 09:25:44    10
2023-05-12 10:10:13     4
2023-05-12 10:10:14     6
2023-05-12 10:17:28    10
2023-05-12 10:46:40     5
2023-05-12 10:46:41     5
2023-05-12 11:06:50    10
2023-05-12 11:24:45     3
2023-05-12 11:30:04     2
2023-05-12 11:51:21    10
2023-05-12 12:02:21    10
2023-05-12 12:21:47    10
2023-05-12 12:24:18    10
2023-05-12 12:24:34     9
2023-05-12 12:24:35    11
2023-05-12 12:27:10    10
2023-05-12 13:01:24     7
2023-05-12 13:29:30    10
2023-05-12 13:36:11    10
2023-05-12 13:48:35    10
2023-05-12 14:01:37    10
2023-05-12 14:09:34    10
2023-05-12 14:32:38    10
2023-05-12 14:40:30    10
2023-05-12 14:58:47     6
2023-05-12 14:58:48     4
2023-05-12 15:00:21     7
2023-05-12 15:00:22     3
2023-05-12 15:02:47    10
2023-05-12 15:15:44     3
2023-05-12 15:17:54    10
2023-05-12 15:34:59     9
2023-05-12 15:37:26    10
2023-05-12 15:40:56    10
2023-05-12 15:47:48    10
2023-05-12 15:54:42    10
2023-05-12 15:54:48    10
2023-05-12 15:55:58    10
2023-05-12 16:06:20     7
2023-05-12 16:06:21     3
2023-05-12 16:13:44    10
2023-05-12 16:45:12    10
2023-05-12 17:32:46    10
2023-05-12 17:51:09    10
2023-05-12 23:10:42    10
2023-05-12 23:30:00     9
2023-05-13 00:51:24     4
2023-05-13 01:37:08    10
2023-05-13 01:57:51    10
2023-05-13 02:26:09     9
2023-05-13 02:34:52     3
2023-05-13 03:18:05    10
2023-05-13 03:18:34    10
2023-05-13 03:20:08    10
2023-05-13 03:28:40     9
2023-05-13 03:35:22    10
2023-05-13 03:51:26    10
2023-05-13 03:52:19    10
2023-05-13 04:02:04    10
2023-05-13 04:22:54    10
2023-05-13 04:35:05    10
2023-05-13 05:00:46     2
2023-05-13 05:08:51    10
2023-05-13 06:16:27    10
2023-05-13 06:27:51    10
2023-05-13 06:39:29    10
2023-05-13 07:10:41    10
2023-05-13 07:11:19     7
2023-05-13 07:11:50    10
2023-05-13 07:40:33    10
2023-05-13 08:16:56     2
2023-05-13 08:16:57     8
2023-05-13 08:55:40    10
2023-05-13 09:07:46    10
2023-05-13 09:16:42    10
2023-05-13 09:21:31     4
2023-05-13 09:23:26    10
2023-05-13 09:28:01     7
2023-05-13 09:33:51    10
2023-05-13 09:34:41    10
2023-05-13 09:44:07     5
2023-05-13 10:12:58     6
2023-05-13 10:33:10     8
2023-05-13 10:39:02    10
2023-05-13 10:56:12    10
2023-05-13 11:20:46    10
2023-05-13 11:41:46     9
2023-05-13 12:03:22     9
2023-05-13 12:20:04     7
2023-05-13 12:24:22    10
2023-05-13 12:37:51    10
2023-05-13 12:40:19    10
2023-05-13 12:54:27    10
2023-05-13 12:55:07     8
2023-05-13 12:56:20    10
2023-05-13 13:04:25     3
2023-05-13 13:04:26     7
2023-05-13 13:37:55    10
2023-05-13 13:39:22    10
2023-05-13 13:45:59    10
2023-05-13 13:53:30    10
2023-05-13 13:59:32    10
2023-05-13 14:06:48    10
2023-05-13 14:26:25    10
2023-05-13 14:41:45    10
2023-05-13 14:54:06     7
2023-05-13 15:06:45    10
2023-05-13 15:11:16    10
2023-05-13 15:23:48    10
2023-05-13 15:32:35    10
2023-05-13 15:33:09     3
2023-05-13 15:57:28     8
2023-05-13 16:27:44    10
2023-05-13 16:34:39     4
2023-05-13 16:34:40    16
2023-05-13 16:50:28    10
2023-05-13 16:57:42     6
2023-05-13 17:21:10    10
2023-05-13 17:21:52    10
2023-05-13 17:56:54    10
2023-05-13 18:47:11    10
2023-05-13 23:00:59    10
2023-05-13 23:33:47    10
2023-05-14 00:18:09    10
2023-05-14 00:24:06     3

In [25]:
# created_at_counts를 DataFrame으로 변환
created_at_counts_df = created_at_counts.reset_index()
created_at_counts_df.columns = ['created_at', 'count']
# created_at을 datetime으로 변환
created_at_counts_df['created_at'] = pd.to_datetime(created_at_counts_df['created_at'])
# created_at을 기준으로 정렬
created_at_counts_df = created_at_counts_df.sort_values(by='created_at')

In [26]:
created_at_counts_df.head()

           created_at  count
0 2023-04-28 13:41:27     10
1 2023-04-28 14:19:21      9
2 2023-04-29 04:43:25     10
3 2023-04-29 13:28:26     10
4 2023-04-29 13:59:53      6

In [27]:
created_at_counts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5316 entries, 0 to 5315
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   created_at  5316 non-null   datetime64[ns]
 1   count       5316 non-null   int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 83.2 KB

In [28]:
created_at_counts_df['count'].value_counts()

count
10    3806
9      264
7      206
8      195
6      191
5      156
4      127
3      123
1      123
2      114
20       4
19       2
17       2
11       1
16       1
18       1
Name: count, dtype: int64

In [29]:
unprocessed = polls_questionpiece[
    (polls_questionpiece['is_voted'] == 1) & (polls_questionpiece['is_skipped'] == 1)
]
print(f"총 {len(unprocessed)}개의 이상 행이 존재합니다.")

총 1127개의 이상 행이 존재합니다.

### is_voted, is_skipped가 다 0인 경우?

In [30]:
polls_questionpiece.head()

       id  is_voted          created_at  question_id  is_skipped
0  998458         1 2023-04-28 12:27:22          252           0
1  998459         1 2023-04-28 12:27:22          244           0
2  998460         1 2023-04-28 12:27:22          183           0
3  998461         1 2023-04-28 12:27:22          101           0
4  998462         1 2023-04-28 12:27:22          209           0

In [31]:
polls_questionreport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51424 entries, 0 to 51423
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           51424 non-null  int64
 1   reason       51424 non-null  object
 2   created_at   51424 non-null  datetime64[ns]
 3   question_id  51424 non-null  int64
 4   user_id      51424 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 2.0+ MB

In [32]:
polls_questionreport.head()

   id                reason          created_at  question_id  user_id
0   1           이 질문은 재미없어요 2023-04-19 06:20:35          250   837556
1   2           이 질문은 재미없어요 2023-04-19 06:58:09          113   837672
2   3       불쾌한 내용이 포함되어 있음 2023-04-19 06:58:17          113   837672
3   4  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:42          119   837922
4   5  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:50          119   837922

In [33]:
polls_question['id'].min(), polls_question['id'].max()

(np.int64(99), np.int64(5133))

In [34]:
polls_questionpiece['question_id'].min(), polls_questionpiece['question_id'].max()

(np.int64(99), np.int64(5133))

In [35]:
polls_questionreport['question_id'].min(), polls_questionreport['question_id'].max()

(np.int64(99), np.int64(5110))

In [36]:
# 조건에 맞는 행 필터링
unprocessed_df = polls_questionpiece[
    (polls_questionpiece['is_voted'] == 0) & 
    (polls_questionpiece['is_skipped'] == 0)
]

# 결과 확인
unprocessed_df.head()

           id  is_voted          created_at  question_id  is_skipped
1084  1015518         0 2023-04-28 13:41:27          268           0
1085  1015519         0 2023-04-28 13:41:27          184           0
1086  1015520         0 2023-04-28 13:41:27          141           0
1087  1015521         0 2023-04-28 13:41:27          172           0
1088  1015522         0 2023-04-28 13:41:27          259           0

In [37]:
unprocessed_df.question_id.nunique(), unprocessed_df.id.nunique()

(4645, 46789)

In [38]:
unprocessed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46789 entries, 1084 to 1265475
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           46789 non-null  int64
 1   is_voted     46789 non-null  int64
 2   created_at   46789 non-null  datetime64[ns]
 3   question_id  46789 non-null  int64
 4   is_skipped   46789 non-null  int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 2.1 MB

In [39]:
unprocessed_df.id.nunique()

46789

In [40]:
polls_questionreport.head()

   id                reason          created_at  question_id  user_id
0   1           이 질문은 재미없어요 2023-04-19 06:20:35          250   837556
1   2           이 질문은 재미없어요 2023-04-19 06:58:09          113   837672
2   3       불쾌한 내용이 포함되어 있음 2023-04-19 06:58:17          113   837672
3   4  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:42          119   837922
4   5  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:50          119   837922

In [41]:
# 신고된 질문 ID 목록
reported_q_ids = polls_questionreport['question_id'].unique()

# 신고된 질문 중 응답 없는 것 필터링
unprocessed_reported = unprocessed_df[unprocessed_df['question_id'].isin(reported_q_ids)]

print(f"응답 없이 신고된 질문 수: {len(unprocessed_reported)}")

응답 없이 신고된 질문 수: 40188

In [42]:
unprocessed_reported.head()

           id  is_voted          created_at  question_id  is_skipped
1084  1015518         0 2023-04-28 13:41:27          268           0
1085  1015519         0 2023-04-28 13:41:27          184           0
1086  1015520         0 2023-04-28 13:41:27          141           0
1087  1015521         0 2023-04-28 13:41:27          172           0
1088  1015522         0 2023-04-28 13:41:27          259           0

In [43]:
unprocessed_reported.id.nunique()

40188

In [44]:
unprocessed_df['id'].nunique()

46789

In [45]:
# 교집합 개수
common_ids = set(unprocessed_reported['id']) & set(unprocessed_df['id'])

print(f"두 DataFrame 간 id 일치 개수: {len(common_ids)}")

두 DataFrame 간 id 일치 개수: 40188

In [46]:
unprocessed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46789 entries, 1084 to 1265475
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           46789 non-null  int64
 1   is_voted     46789 non-null  int64
 2   created_at   46789 non-null  datetime64[ns]
 3   question_id  46789 non-null  int64
 4   is_skipped   46789 non-null  int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 2.1 MB

In [47]:
unprocessed_df.question_id.nunique()

4645

In [48]:
# 1. 신고된 question_id만 따로
reported_q_ids = polls_questionreport['question_id'].unique()

# 2. 신고 안 된 미응답만 추출
unprocessed_unreported = unprocessed_df[~unprocessed_df['question_id'].isin(reported_q_ids)]

print(f"신고도 안 되고 응답도 안 된 질문 수: {len(unprocessed_unreported)}")

신고도 안 되고 응답도 안 된 질문 수: 6601

### 신고를 한 다음 질문부터는 정상적으로 이어지나?

In [50]:
# 신고된 질문 ID 목록
reported_q_ids = polls_questionreport['question_id'].unique()

# 신고된 question_id를 포함하는 조각 중 미응답 조각
reported_unprocessed = polls_questionpiece[
    (polls_questionpiece['question_id'].isin(reported_q_ids)) &
    (polls_questionpiece['is_voted'] == 0) &
    (polls_questionpiece['is_skipped'] == 0)
]
print(f"신고된 질문 중 응답 없는 조각 수: {len(reported_unprocessed)}")

신고된 질문 중 응답 없는 조각 수: 40188

In [51]:
# questionset에서 questionpiece_id_list explode
polls_questionset["question_piece_id_list"] = polls_questionset["question_piece_id_list"].apply(ast.literal_eval)
qs_exploded = polls_questionset.explode("question_piece_id_list").rename(columns={"question_piece_id_list": "questionpiece_id"})
qs_exploded["questionpiece_id"] = qs_exploded["questionpiece_id"].astype(int)

# 미응답 신고 조각에 해당하는 질문 세트 ID 확보
reported_unprocessed = reported_unprocessed.merge(
    qs_exploded[["id", "user_id", "questionpiece_id"]],
    left_on="id", right_on="questionpiece_id", how="left"
)

In [52]:
reported_unprocessed.head()

      id_x  is_voted          created_at  question_id  is_skipped    id_y  user_id  questionpiece_id
0  1015518         0 2023-04-28 13:41:27          268           0  101523   850120           1015518
1  1015519         0 2023-04-28 13:41:27          184           0  101523   850120           1015519
2  1015520         0 2023-04-28 13:41:27          141           0  101523   850120           1015520
3  1015521         0 2023-04-28 13:41:27          172           0  101523   850120           1015521
4  1015522         0 2023-04-28 13:41:27          259           0  101523   850120           1015522

In [55]:
# 해당 세트의 다른 조각들 불러오기
related_sets = qs_exploded[qs_exploded["questionpiece_id"].isin(reported_unprocessed["id_y"])]


# 다른 조각의 응답 여부 확인 (polls_questionpiece와 다시 merge)
other_pieces = related_sets.merge(polls_questionpiece, left_on="questionpiece_id", right_on="id", how="left")

# 신고된 조각 이후 조각 중 정상 응답한 것만 필터
responded_after = other_pieces[
    (other_pieces["is_voted"] == 1) | (other_pieces["is_skipped"] == 1)
]
responded_after.head()

     id_x  questionpiece_id        opening_time status        created_at_x  user_id       id_y  is_voted        created_at_y  question_id  is_skipped
0  100496           1005253 2023-04-28 13:42:21      F 2023-04-28 12:52:21   849443  1005253.0       1.0 2023-04-28 12:52:21        128.0         0.0
1  105265           1052942 2023-04-28 18:23:34      F 2023-04-28 17:33:34   850718  1052942.0       1.0 2023-04-28 17:33:34        312.0         0.0
2  105298           1053269 2023-04-28 18:29:19      F 2023-04-28 17:39:19   850412  1053269.0       1.0 2023-04-28 17:39:19        199.0         0.0
3  108676           1087050 2023-04-29 04:22:13      F 2023-04-29 03:32:13   850610  1087050.0       1.0 2023-04-29 03:32:13        285.0         0.0
4  111467           1114958 2023-04-29 07:12:38      F 2023-04-29 06:22:38   849559  1114958.0       1.0 2023-04-29 06:22:38        210.0         0.0

In [56]:
responded_after.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 74
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_x              61 non-null     int64
 1   questionpiece_id  61 non-null     int64
 2   opening_time      61 non-null     datetime64[ns]
 3   status            61 non-null     object
 4   created_at_x      61 non-null     datetime64[ns]
 5   user_id           61 non-null     int64
 6   id_y              61 non-null     float64
 7   is_voted          61 non-null     float64
 8   created_at_y      61 non-null     datetime64[ns]
 9   question_id       61 non-null     float64
 10  is_skipped        61 non-null     float64
dtypes: datetime64[ns](3), float64(4), int64(3), object(1)
memory usage: 5.7+ KB

In [58]:
import pandas as pd

# 1. 신고된 question_id 목록 추출
reported_q_ids = polls_questionreport['question_id'].unique()

# 2. 신고된 question_id 중에서 is_voted == 0 and is_skipped == 0인 questionpiece 추출
reported_unprocessed = polls_questionpiece[
    (polls_questionpiece['question_id'].isin(reported_q_ids)) &
    (polls_questionpiece['is_voted'] == 0) &
    (polls_questionpiece['is_skipped'] == 0)
]

# 3. 신고된 questionpiece.id가 포함된 questionset 찾기
target_sets = polls_questionset[
    polls_questionset['question_piece_id_list'].apply(
        lambda x: any(qp_id in x for qp_id in reported_unprocessed['id'])
    )
]

# 4. 각 questionset에서 신고된 질문 이후에 정상 응답이 있었는지 확인
count_with_response = 0

for _, row in target_sets.iterrows():
    question_ids = row['question_piece_id_list']
    
    # 해당 세트의 질문조각 전체
    subset = polls_questionpiece[polls_questionpiece['id'].isin(question_ids)].copy()
    
    # 신고된 조각이 세트 내 몇 번째인지
    reported_ids_in_set = [i for i, qid in enumerate(question_ids) if qid in reported_unprocessed['id'].values]
    
    if not reported_ids_in_set:
        continue
    
    # 가장 뒤에 등장한 신고된 조각 이후의 조각들만 필터링
    last_reported_index = max(reported_ids_in_set)
    question_ids_after = question_ids[last_reported_index + 1:]
    
    # 이후 조각들에서 응답 또는 스킵이 하나라도 있었는지
    remaining = polls_questionpiece[polls_questionpiece['id'].isin(question_ids_after)]
    
    normal_responses = remaining[
        ((remaining['is_voted'] == 1) & (remaining['is_skipped'] == 0)) |
        ((remaining['is_voted'] == 0) & (remaining['is_skipped'] == 1))
    ]
    
    if len(normal_responses) > 0:
        count_with_response += 1

print(f"✅ 신고된 질문 이후 정상적으로 응답한 세트 수: {count_with_response}")

✅ 신고된 질문 이후 정상적으로 응답한 세트 수: 2

In [59]:
normal_responses.head()

Empty DataFrame
Columns: [id, is_voted, created_at, question_id, is_skipped]
Index: []